### PR TITLE
GH-1259 Improves Cell propEdit filter

### PR DESCRIPTION
**Pull request by jbrundage**
Fixes GH-1259

@GordonSmith @mlzummo @dtsnell4 Please review

http://rawgit.com/jbrundage/Visualization/GH-1259/demos/dermatology.html?src/layout/Grid&designMode=1
Signed-off-by: jay <jbrundage372@gmail.com>

### CODE REVIEW

**Comment by jbrundage** [comment]
Click a Cell while in design mode to see more intuitive PropertyEditor filtering

**Comment by GordonSmith** [comment]
@jbrundage should this target 1.10?

**Comment by dtsnell4** [comment]
@jbrundage very nice, but needs rebase

**Comment by jbrundage** [comment]
Closed in favor of #1274

**Pull request closed without merging**
