### PR TITLE
Slippery Map

### PR DESCRIPTION
**Pull request by GordonSmith**

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage @mlzummo @dtsnell4 Please Review:
http://rawgit.com/GordonSmith/Visualization/MAP_SLIPPERY/demos/dermatology.html?src/map/Graticule
http://rawgit.com/GordonSmith/Visualization/MAP_SLIPPERY/demos/dermatology.html?src/map/OpenStreet
http://rawgit.com/GordonSmith/Visualization/MAP_SLIPPERY/demos/dermatology.html?src/map/ChoroplethContinents
http://rawgit.com/GordonSmith/Visualization/MAP_SLIPPERY/demos/dermatology.html?src/map/ChoroplethCountries
http://rawgit.com/GordonSmith/Visualization/MAP_SLIPPERY/demos/dermatology.html?src/map/ChoroplethStates
http://rawgit.com/GordonSmith/Visualization/MAP_SLIPPERY/demos/dermatology.html?src/map/ChoroplethCounties
http://rawgit.com/GordonSmith/Visualization/MAP_SLIPPERY/demos/dermatology.html?src/map/GeoHash
http://rawgit.com/GordonSMith/Visualization/MAP_SLIPPERY/demos/dermatology.html?src/map/Pins
http://rawgit.com/GordonSMith/Visualization/MAP_SLIPPERY/demos/dermatology.html?src/map/Layered

**Comment by jbrundage** [comment]
@GordonSmith Nice stuff! 

Could you make the test_Sample layers array into a widgetArray publish param so they can be displayed in the PropertyEditor?

**Comment by GordonSmith** [comment]
Added Heat support:  http://rawgit.com/GordonSmith/Visualization/MAP_SLIPPERY/demos/dermatology.html?src/map/Heat

**Comment by GordonSmith** [comment]
Added Graph support: http://rawgit.com/GordonSmith/Visualization/MAP_SLIPPERY/demos/dermatology.html?src/map/Graph

**Comment by GordonSmith** [comment]
Experimental:  Working with google maps as base layer:
http://rawgit.com/GordonSmith/Visualization/MAP_SLIPPERY/demos/dermatology.html?src/map/GMap2

**Comment by mlzummo** [comment]
on GMap2 when you zoom out it gets out of sync

**Comment by GordonSmith** [comment]
@mlzummo - Fixed GMap lag issue and improved zoomed out behavior (it now works the same as GMapHeat and GMapGraph) - still needs fixing, but it is now a GMap and not related to this PR...

**Comment by mlzummo** [comment]
looks good

**Comment by mlzummo** [comment]
looks good

**Pull request merged**
