### PR TITLE
GH-1330 Enable Table Pivoting

### PR DESCRIPTION
**Pull request by GordonSmith**
Allow conditional disabling of properties in the property editor.

Fixes GH-1330

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage @mlzummo Please Review
http://rawgit.com/GordonSmith/Visualization/GH-1330/demos/dermatology.html?src/other/Table&pivot=false

Note:  Notice how turning on the pivot option now disables some other properties...

**Comment by jbrundage** [comment]
Excellent! The disable feature will be very useful.

@GordonSmith Currently the table grows wider and wider when toggling pivot on and off a few times.

**Comment by GordonSmith** [comment]
@jbrundage So it does... I suspect the same will happen if the data changes, gonna test.

**Comment by GordonSmith** [comment]
@jbrundage see https://github.com/hpcc-systems/Visualization/issues/1332 (the pivot is simply exposing this issue)...

**Comment by mlzummo** [comment]
@GordonSmith status?

**Comment by GordonSmith** [comment]
Waiting on review

**Comment by jbrundage** [comment]
@GordonSmith This looks good to me

**Comment by mlzummo** [comment]
did we fix:  Currently the table grows wider and wider when toggling pivot on and off a few times. ?

**Comment by jbrundage** [comment]
No, evidently its going to be treated as a separate issue (it is a separate issue).

**Comment by mlzummo** [comment]
ok then looks good ready to pull

**Pull request merged**
