### PR TITLE
GH-1319 XYAxis rendering invalid shapes

### PR DESCRIPTION
**Pull request by GordonSmith**
* Selection brush + no data rendered invalid rect
* Columns rendering data beyond max columns

Fixes GH-1319

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo Please Review

**Comment by mlzummo** [comment]
does this have to do with ZN graph issue at all?

**Comment by GordonSmith** [comment]
Yes - it was causing the console, error messages.

**Comment by mlzummo** [comment]
@GordonSmith this does not seem to be fixing the ZN_Graph (relevent dash console log errors)

**Comment by GordonSmith** [comment]
It should have removed some of them...  I will investigate more.

**Comment by GordonSmith** [comment]
@mlzummo I just re-tested with candidate_zn_graph and this does "fix" many of the console errors.

**Comment by mlzummo** [comment]
@GordonSmith have you had a chance to look at the code base they are using for their dash project?

**Comment by GordonSmith** [comment]
I am assuming its:  https://github.com/hpcc-systems/Visualization/tree/candidate_zn_graph

**Comment by GordonSmith** [comment]
@dineshshetye Please Review

**Comment by jbrundage** [comment]
@GordonSmith Looks good to me

**Pull request merged**
