### PR TITLE
GH-1868 Disable pins "bring to top" for IE

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes GH-1868

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage @mlzummo Please Review

**Comment by jbrundage** [comment]
Looks good

**Comment by jbrundage** [comment]
@GordonSmith Actually... the mouseover event callback is causing the pin icon path element to display ontop of the pin icon (text element). The onClick and onMouseover event callbacks should be bound to the **g.pin** instead of the **path.data**. I'll issue a PR for this either later tonight or tomorrow.

**Comment by GordonSmith** [comment]
@jbrundage That would be a different issue to this one though (no mouse out event on IE 11)?

**Comment by jbrundage** [comment]
@GordonSmith You're right. This change looks good.

**Pull request merged**
