### PR TITLE
Adds progress bar to ChartPanel

### LINKED ISSUE #2336: ChartPanel:   Loading/Progress Indicator
Some sort of loading indicator:  thin bar along the top like GitHubs?

### PR DESCRIPTION
**Pull request by jbrundage**
Fixes #2336 

@GordonSmith please review

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage looks like you have managed to include a bunch of other changes?

**Comment by jbrundage** [comment]
Hmm that's odd... I'll have to figure out what happened

**Comment by jbrundage** [comment]
@GordonSmith this one is ready

**Comment by GordonSmith** [comment]
Closing in favor of:  https://github.com/hpcc-systems/Visualization/pull/2405

**Pull request closed without merging**
