### PR TITLE
Grid Layout Visual Editor

### PR DESCRIPTION
**Pull request by GordonSmith**
Allow user to drag and drop widgets on the Grid Layout.

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo, @dineshshetye Please Review.  

http://rawgit.com/GordonSmith/Visualization/DND-1.0.0/demos/dermatology.html?src/layout/Grid
(and turn on the designMode option)

**Comment by GordonSmith** [comment]
Fixes #160

**Comment by mlzummo** [comment]
Looks Good

**Comment by GordonSmith** [comment]
(Rebased for merge)

**Pull request merged**
