### PR TITLE
Add support for show/hide tabs on tabbed layout.

### PR DESCRIPTION
**Pull request by GordonSmith**
Surface needs to check for modified on some properties.

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo Please Review

**Comment by jbrundage** [comment]
Fantastic... this does fix the problem. Switching between themes now works as expected.

**Comment by GordonSmith** [comment]
Is this good to pull?

**Comment by jbrundage** [comment]
Yes, it looks good to me.

**Pull request merged**
