### PR TITLE
GH-320 Dynamic Files + Marshaller

### LINKED ISSUE #320: Script error while loading HIPIE DDL
Creating Graphmarshaller throws the following error with the latest build of Visualisation
image
With older codebases, Visualisation renders without errors

### PR DESCRIPTION
**Pull request by GordonSmith**
Fix regression introduced with the UMD re-factoring.

Fixes #320

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@dhanasiddharth Please Review

**Comment by dhanasiddharth** [comment]
As our HPCC cluster is down, I coldn't confirm the fix now. It's off for us here on May 1st. Will update the status on Monday

**Comment by GordonSmith** [comment]
...no - that fix is in a different PR already - this pull request is targeting 0.9.4 and doesn't have your shim...
https://github.com/hpcc-systems/Visualization/pull/321

**Comment by dhanasiddharth** [comment]
@GordonSmith This fixes our issue. Thanks.

**Pull request merged**
