### PR TITLE
feat: Added features to Modal/TitleBar

### PR DESCRIPTION
**Pull request by jbrundage**
Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

### CODE REVIEW

**Comment by jbrundage** [comment]
image

**Comment by jbrundage** [comment]
@GordonSmith I've tested it with dashy
Here's the sample I created for TitleBar:
image

**Comment by GordonSmith** [comment]
@jbrundage failing travis

**Comment by GordonSmith** [comment]
@jbrundage bump

**Comment by GordonSmith** [comment]
@jbrundage Failing travis

**Comment by jbrundage** [comment]
@GordonSmith it's passing TravisCI now

**Comment by jbrundage** [comment]
This PR had a rather nasty set of conflicts. I'll need to revisit this one as the dashy title bars aren't looking quite right.

**Pull request closed without merging**
