### PR TITLE
Special case Graph Double Click for RAMPs Phase I

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@drealeed Please Review

**Comment by drealeed** [comment]
I get what's going on in the code; what would need to be put in the DDL to activate the double-click select?

**Comment by GordonSmith** [comment]
Just the usual "select"

**Comment by drealeed** [comment]
reviewed & signed off

**Pull request merged**
