### PR TITLE
Remove "theme" support from Publish Params.

### PR DESCRIPTION
**Pull request by GordonSmith**
This feature was not used.

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage Please Review

**Comment by jbrundage** [comment]
@GordonSmith I think the themes could play a big part in the acceptance of this framework in the long run. The idea was (originally) to allow themes to be the take-away from the "dermatology layer" and applied within an app to provide styling. I was using a theme within the Avenger app, but Claudio preferred to configure the publish parameter values from within the DSP.

**For apps that don't use DSP** a theme is what will allow a non-technical person style their charts.

**Comment by GordonSmith** [comment]
@jbrundage I agree 100% - but this change does not affect your theme support and the way you have implemented it (which is why I am removing it) - the PR title could be better...

**Comment by GordonSmith** [comment]
@jbrundage Please Review (see above comments)

**Comment by jbrundage** [comment]
@GordonSmith It seems to work well enough. 
Styles are no longer reset to their default values when switching between themes, but that isn't necessarily an issue.

**Pull request merged**
