### PR TITLE
GH-1214 Empty Google Chart Error

### PR DESCRIPTION
**Pull request by GordonSmith**
Create / Remove Google Charts on demand.

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by mlzummo** [comment]
so far with my tests this looks ok ...

**Comment by mlzummo** [comment]
if you delete the columns first and then the data it errors but not the other way around which is good and when u delete both its fine ...

**Comment by mlzummo** [comment]
should prolly check that there is a correct number of columns matching data?

**Comment by GordonSmith** [comment]
@mlzummo:  If there is bad column/data info then we should still throw it at the google chart and let it render it or display an error (as it might still render something?)

Also in other charts we will have extra "columns" in the data structure which is used in the click event, but not used in the render process...  So we can't check generically (its basically an embedded payload).

**Comment by mlzummo** [comment]
ok looks good then

**Pull request merged**
