### PR TITLE
Second y axis test amcharts 3

### PR DESCRIPTION
**Pull request by mlzummo**
@GordonSmith Please take a look at what i did with creating a new "Axis" based on widget so that we can now store params per axis without lots of extra code or Params

@jbrundage @dtsnell4 Whats your thoughts on this as well?

### CODE REVIEW

**Comment by mlzummo** [comment]
https://github.com/hpcc-systems/Visualization/pull/1081/files#diff-59a5d9625e214642495d08c22efe7a60R31

**Comment by mlzummo** [comment]
amchart_Column.xAxis[0].fontSize("10");    :)

**Comment by mlzummo** [comment]
this method will closely aproximate what HPCC Charts will be doing with multiple charts being each Axis ... stil need a method on deciding which data goes to which chart  or will we have somethinglike this in HPCC and the others    widget.xAxis[0].data([]) ?

**Comment by mlzummo** [comment]
CommonSerial.prototype._additionalPP = ["xAxis","yAxis"];   this variable can be standard such that discover function and propertyeditor know what to do with it

**Comment by mlzummo** [comment]
only thing im not sure about yet is how will serialization be treated this way?

**Comment by mlzummo** [comment]
@GordonSmith bump

**Comment by GordonSmith** [comment]
We do have a publish type of WIdgetArray,  And your Axis won't be deserializable without being in its own file.

**Pull request closed without merging**
