### PR TITLE
Additions and Updates to the apps in the Sample Site Directory

### PR DESCRIPTION
**Pull request by dtsnell4**
@GordonSmith @mlzummo @jbrundage  Please review

Signed-off-by: Mathew Zummo <mzummo@gmail.com>

Signed-off-by: Dan Snell Dan.Snell@lexisnexis.com

### CODE REVIEW

**Comment by GordonSmith** [comment]
I don't think the "Popup.css + Popup.js" files should be in this PR.  Otherwise if Jaman or Matt are happy with the app/* changes I will pull.

**Comment by mlzummo** [comment]
@GordonSmith this PR includes a demo of the popup thats why it has it. Do any mods need to be done on popup as of right now to get that seperate PR pulled

**Comment by mlzummo** [comment]
https://github.com/hpcc-systems/Visualization/pull/577    (popup PR)

**Comment by dtsnell4** [comment]
@mlzummo @jbrundage I removed the Popup.js files from the "src" directory and put them in a "tempsrc" directory in SampleSite so that the demo page continues to function.  I will add it back once it is merged.  Once you guys are ok with everything else we can just ask Gordon to merge it.  

Matt, I cannot squash these commits because I merged in another branch :-/  Sorry, I have to remember that.

**Pull request closed without merging**
