### PR TITLE
GH-2052 Get state fails for items with no datasource

### PR DESCRIPTION
**Pull request by GordonSmith**
(forms)

Fixes GH-2052

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jchambers-ln @jbrundage Please Review

**Comment by jchambers-ln** [comment]
looks good to me

**Comment by jbrundage** [comment]
Yep, looks good

**Comment by GordonSmith** [comment]
Waiting on @Mohammed-Idris-K-J to re-test

**Pull request merged**
