### PR TITLE
GH-1045 GMap Unit Tests failing on travis

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes GH-1045

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo Please Review

**Comment by mlzummo** [comment]
@GordonSmith looks good, can you explain why that works?

**Comment by mlzummo** [comment]
https://travis-ci.org/hpcc-systems/Visualization/builds/86407574#L481

still failing

**Comment by GordonSmith** [comment]
Upping the node.js version number as well:  @mlzummo Please Review

**Comment by mlzummo** [comment]
@GordonSmith looks good, can we pull this and megachart fix?

**Comment by GordonSmith** [comment]
Thats next!

**Pull request merged**
