### PR TITLE
feat: Add Cooccurence widget

### PR DESCRIPTION
**Pull request by jbrundage**
Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

## Checklist:
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit message includes a "fixes" reference if appropriate.
  - [x] The commit is signed.
- [x] The change has been fully tested:
  - [x] I have viewed all related gallery items
  - [ ] I have viewed all related dermatology items
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised new issues to address them separately

## Testing:
Tested samples in the gallery playground

### CODE REVIEW

**Comment by jbrundage** [comment]
It's responsive down to very small resolutions (depending on the data)
image

And can display square cells or stretch to fit its target
image
image

**Comment by jbrundage** [comment]
@GordonSmith I've moved Cooccurence to graph and modified it to accept the graph_Graph data shape as we discussed yesterday.

I added a few sorting modes as well.

**Comment by jbrundage** [comment]
Here's one use case to consider where the column labels don't match the row labels:
image

**Comment by GordonSmith** [comment]
@jbrundage I think that chart is actually very similar to a "Punchcard Chart" and I would certainly re-use the X-Y Axis base class for it?

**Comment by GordonSmith** [comment]
@jbrundage this PR seems to have a lot of unrelated files in in it?

**Pull request closed without merging**
