### PR TITLE
GH-587 Form enter should submit

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes GH-587

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo Please Review

**Comment by mlzummo** [comment]
does not work as expected (submit press results in this):
image

current code does this:
image

**Comment by mlzummo** [comment]
i think clear is still being pressed .....on this code ...

**Comment by mlzummo** [comment]
change button order to fix this or revert to my code/PR

**Comment by mlzummo** [comment]
http://rawgit.com/GordonSmith/Visualization/GH-587/demos/marshaller/index.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20150721-134947&ResultName=leeddx_filtertest_Comp_Ins002_DDL

**Comment by mlzummo** [comment]
@GordonSmith

**Comment by GordonSmith** [comment]
@mlzummo Please Re-review

**Comment by mlzummo** [comment]
looks good

**Comment by GordonSmith** [comment]
Retargetting:  https://github.com/hpcc-systems/Visualization/pull/637

**Pull request closed without merging**
