### PR TITLE
Table Widget Fixed First Column

### PR DESCRIPTION
**Pull request by dtsnell4**
Added fixedColumns as publish parameter so user can choose either fixed first column, fixed header, or both.

Signed-off-by: Dan Snell <Dan.Snell@lexisnexis.com>

### CODE REVIEW

**Comment by dtsnell4** [comment]
@GordonSmith @mlzummo @jbrundage Please review

**Comment by dtsnell4** [comment]
Closing, Wrong branch

**Comment by GordonSmith** [comment]
@dtsnell4 - can you target this for 1.6.0?

**Comment by dtsnell4** [comment]
Yes

**Pull request closed without merging**
