### PR TITLE
GH-1510 Add HexBin chart

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes GH-1510

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage @mlzummo Please Review

http://rawgit.com/GordonSmith/Visualization/GH-1510/demos/dermatology.html?src/chart/HexBin

**Comment by jbrundage** [comment]
@GordonSmith Looks lovely, but its default data should display a practical use case.

Also, shouldn't this have a X, Y and Z axes?

**Comment by GordonSmith** [comment]
@jbrundage No z.  Its just a scatter chart, but aggregates all the local points into a "hex bin" the color is defined by the amount of points within the bin.

**Comment by mlzummo** [comment]
this looks good

**Pull request merged**
