### PR TITLE
Dermatology fails to load when opened in web browser with no web server.

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage @mlzummo Please Review

**Comment by mlzummo** [comment]
page loads ... however these errors occur in chrome:  

XMLHttpRequest cannot load file:///C:/Users/{USER_NAME}/Downloads/test/Visualization/widgets/src/common/Shape.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
----------------------------------------------
----------------------------------------------
text.js:308 Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///C:/Users/{USER_NAME}/Downloads/test/Visualization/widgets/src/common/Shape.js'.
----------------------------------------------
----------------------------------------------
text.js:308 XMLHttpRequest cannot load file:///C:/Users/{USER_NAME}/Downloads/test/Visualization/widgets/src/google/Pie.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
----------------------------------------------
----------------------------------------------
text.js:308 Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///C:/Users/{USER_NAME}/Downloads/test/Visualization/widgets/src/google/Pie.js'.

**Comment by GordonSmith** [comment]
Yes - but they are now happening within the "try/catch" block - so the page still works, but you don't get to see the source code (which is the compromise).

**Comment by mlzummo** [comment]
ok thats what I'm seeing on my end... looks good

**Pull request merged**
