### PR TITLE
GH-844 Themes not resetting correctly

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes GH-844

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage Please Review

**Comment by jbrundage** [comment]
Something is preventing the surfaceBorderWidth (and maybe other params in the themes) from being applied.

**Comment by GordonSmith** [comment]
Is this just here or in general?

**Comment by jbrundage** [comment]
It's just in this PR

**Comment by jbrundage** [comment]
I've been looking through the diffs trying to make sense of the issue...

**Comment by jbrundage** [comment]
@GordonSmith This PR looks good to me.

I found the issue with the surfaceBorderWidth (and radius), it's unrelated to this PR.
https://github.com/GordonSmith/Visualization/blob/GH-844/src/layout/Surface.js#L91-L93

**Comment by jbrundage** [comment]
@GordonSmith Looks/works good

**Pull request merged**
