### PR TITLE
GH-2311

### PR DESCRIPTION
**Pull request by GordonSmith**
Click event should call row to object.
Commoned up the label and value extraction code.

Foxes GH-2311

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage Please Review (be warned the GitHub compare is not doing a very good job here).

**Comment by jbrundage** [comment]
@GordonSmith I think **lookupFieldText** should be added at the common_Widget level, no?

**Comment by GordonSmith** [comment]
I did have that thought as well - but didn't want to go there on a point release...

**Comment by jbrundage** [comment]
Looks good to me

**Pull request merged**
