### PR TITLE
Google Maps needs to remove all elements on remove.

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage, @mlzummo Please Review

**Comment by mlzummo** [comment]
works, however the "widget-wrapper" (target element) has its style property modified and that is not reverted, i am not sure if that will be/is an issue

**Comment by GordonSmith** [comment]
Its the other way round - the google maps change it to a bland color and I am simply removing it...

**Comment by mlzummo** [comment]
image

**Comment by mlzummo** [comment]
image

**Comment by GordonSmith** [comment]
The only change I see there is the removal of the background-color?  (which was added by the google chart...)

**Comment by mlzummo** [comment]
div->widget-wrapper should not have any styling after widget removal because it is only applied when the widget is rendered, I believe

**Comment by GordonSmith** [comment]
I shall look further - but the "width:100%; height 100vh" looks an awful lot like my HelloWorld styling!

**Comment by mlzummo** [comment]
the width and height is from the hello world, that should be the only styling left on removal.

**Pull request closed without merging**
