### PR TITLE
AMCharts Common Serial: Y axis formatter will no longer be stored on …

### PR DESCRIPTION
**Pull request by GordonSmith**
…the main context, and added a closure wrapper around the label formatter. Previously, as each Y formatter was created, it clobbered any previous formatter (including the X axis). Additionally, for charts with multiple Y axis, the label formatter was always processing the last most created Y axis, instead of the corresponding Y axis.

### CODE REVIEW

**Comment by GordonSmith** [comment]
@clewisln - I rebased your master branch onto candidate-1.16.x and issued this PR - can you eyeball the changes to make sure they look correct and I will review.

**Comment by GordonSmith** [comment]
@jbrundage Can you test?

**Comment by clewisln** [comment]
looks good to me, other than the travis fail

**Comment by GordonSmith** [comment]
@clewisln ```gulp lint``` in the root folder will show why its failing.

**Comment by clewisln** [comment]
I fixed the lint problems. Some unit tests are failing, however.

**Comment by GordonSmith** [comment]
Unit tests are an issue on the candidate-1.16.x branch and will be removed shortly.  I also fixed lint issue on this PR.

**Comment by jbrundage** [comment]
Ah sorry I missed this thread. @clewisln @GordonSmith I'll put together a
test to compare the capabilities of each widget that supports individual
axis parameters

**Pull request merged**
