### PR TITLE
Adds a test to load widgets into a div

### PR DESCRIPTION
**Pull request by anmoljagetia**
Presently, this test is written to ensure all widgets can be loaded into a test page, with the default testData method called on them. Presently, all the tests pass except for the Edge.js file.

### CODE REVIEW

**Comment by GordonSmith** [comment]
Can you improve the commit message to clearly state the test you are doing.

**Comment by anmoljagetia** [comment]
Can I add a detailed description here?

**Comment by GordonSmith** [comment]
Needs to be in the commit.

**Comment by GordonSmith** [comment]
@anmoljagetia Can you also add a "title" to each DIV - some of them are blank, and I have no knowing which one it is.

**Comment by GordonSmith** [comment]
Closing as a variant has already been added to master.

**Pull request closed without merging**
