### PR TITLE
GH-1316 MARSHALLER_PERSIST_FIX

### PR DESCRIPTION
**Pull request by mlzummo**
@GordonSmith @jbrundage

Please Review ... i think we need a more universal way of fixing this ... but this in the meantime fixes this specific issue

Fixes DSP MARSHALLER/PERSIST issue
Fixes GH-1316

Signed-off-by: Mathew Zummo <mzummo@gmail.com>

### CODE REVIEW

**Comment by mlzummo** [comment]
@GordonSmith @jbrundage looking for comments on better ideas?

**Comment by jbrundage** [comment]
Something like this should work universally...
```javascript
var widgetArr = [];
    Persist.widgetWalker(this,function(w){
        widgetArr.push(w);
    });
    
    this.marshaller = new HipieDDL.Marshaller()
        .proxyMappings(this.proxyMappings())
        .widgetMappings(d3.map(widgetArr, function (d) {
            return d.id();
        }))
        .on("commsError", function (source, error) {
            context.commsError(source, error);
        })
    ;
```

**Comment by mlzummo** [comment]
yea i was thinking that, thanks ill give that a shot

**Comment by mlzummo** [comment]
@GordonSmith @jchambers-ln worked like a charm ready to pull

**Pull request merged**
