### PR TITLE
Minor browser incompatibility.

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage Please Review

**Comment by mlzummo** [comment]
what browser does this change effect?

**Comment by GordonSmith** [comment]
IE + Safari - the "setAttribute" workaround only avoids the error.

**Comment by mlzummo** [comment]
tested, looks good

**Comment by jbrundage** [comment]
Good find... looks good

**Pull request merged**
