### PR TITLE
Sync URL with property selection.

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage Please review - just a small convenience.

**Comment by jbrundage** [comment]
@GordonSmith Good idea... looks good

**Comment by jbrundage** [comment]
@GordonSmith Oops... it looks like this merge broke dermatology.html (when viewing anything with ddlUrl etc)

http://rawgit.com/hpcc-systems/Visualization/candidate-1.10.0/demos/dermatology.html?src/marshaller/Graph.databomb

**Comment by mlzummo** [comment]
should prolly just make ddlUrl not work with _GET string

**Comment by GordonSmith** [comment]
I suspect this will fix it:  https://github.com/hpcc-systems/Visualization/pull/1272

**Comment by jbrundage** [comment]
@GordonSmith It didn't fix the issue

**Comment by mlzummo** [comment]
that didnt fix the issue ..

**Comment by jbrundage** [comment]
@GordonSmith I believe the ddlUrl parameter is too large to display in the URL (which is what's causing the issue)

**Pull request merged**
