### PR TITLE
GH-740 & GH-741 Table Formatting

### PR DESCRIPTION
**Pull request by dtsnell4**
Adds formatting for numbers, strings and dates, including publish parameters for right/left/center justification for each type.

Fixes GH-740
Fixes GH-741

Signed-off-by: Dan Snell <Dan.Snell@lexisnexis.com>

### CODE REVIEW

**Comment by dtsnell4** [comment]
@GordonSmith @mlzummo @jbrundage Please review

**Comment by mlzummo** [comment]
@GordonSmith i think were ok with this

**Comment by mlzummo** [comment]
@dtsnell4 failing lint

**Comment by dtsnell4** [comment]
@GordonSmith @mlzummo lint error fixed

**Comment by mlzummo** [comment]
waiting to hear back from dinesh, can you place a link in this PR?

**Comment by dtsnell4** [comment]
http://rawgit.com/dtsnell4/Visualization/GH-740_Table_Formatting/demos/dermatology.html?src/other/Table.formatted

You initially cannot see the table due to the fixedSize bug, which will be fixed when this PR gets merged https://github.com/hpcc-systems/Visualization/pull/1091

For now, just click the fixedSize checkbox twice and the table will show up.

**Comment by GordonSmith** [comment]
@mlzummo @jbrundage Please review

**Pull request closed without merging**
