### PR TITLE
SVG Surface Button Issue

### PR DESCRIPTION
**Pull request by GordonSmith**
Surface Button Container is failing on the test page.

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo Please Review - I am not sure what the actual cause is, but suspect the "offset" is invalid when you have SVG Widget in SVG Widget.

**Comment by GordonSmith** [comment]
@mlzummo - I am pretty sure this is an IE specific issue you may want to investigate and provide a better fix, but this is breaking master at the moment...

**Comment by mlzummo** [comment]
@GordonSmith 
I am not seeing any issue currently? can you link me to whats being broken?

image

**Comment by mlzummo** [comment]
the click events in IE arent being registered though on those buttons

**Comment by GordonSmith** [comment]
Open http://rawgit.com/hpcc-systems/Visualization/master/demos/test.html?composition in IE

**Comment by mlzummo** [comment]
ok the fix looks good

**Pull request merged**
