### PR TITLE
Fix ESP Response

### PR DESCRIPTION
**Pull request by GordonSmith**
Convert numbers to Numbers.
Trim strings.

Fixes GH-588
Fixes GH-585

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@drealeed, @mlzummo Please Review
Drea if you can test the Roxie response case, similar to this:  http://rawgit.com/GordonSmith/Visualization/NUMERIC_TRIM/demos/marshaller/index.html?Hostname=10.173.147.1&amp;Port=8010&amp;Protocol=http&amp;Wuid=W20150721-134947&amp;ResultName=leeddx_filtertest_Comp_Ins002_DDL

**Comment by mlzummo** [comment]
@GordonSmith your link got html encoded can you resubmit the link

**Comment by mlzummo** [comment]
looks good

**Comment by drealeed** [comment]
Roxie test: http://rawgit.com/GordonSmith/Visualization/NUMERIC_TRIM/demos/marshaller/index.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20150806-114911&ResultName=leeddx_testnumsort_Comp_Ins365_DDL

**Comment by mlzummo** [comment]
sorting of table column when header pressed still doesnt work (marshaller and table sorting algo differ and need to match)

**Comment by mlzummo** [comment]
6 vs 06? if thats ok then nevermind

**Comment by GordonSmith** [comment]
@mlzummo Can you retest - the Roxie call was not being "fixed" correctly, but should be now.

**Comment by mlzummo** [comment]
yes it works

**Pull request merged**
