### PR TITLE
Databomb Support

### PR DESCRIPTION
**Pull request by GordonSmith**
Add databomb support to HTML marshaller.
Add Databomb Support to Graph Marshaller

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage @gururx Please Review (this is the same as the Previous Graph Databomb PR, but includes databomb support for the HTML marshaller and is based for upstream and not symposium)

**Comment by mlzummo** [comment]
Uncaught SyntaxError: Unexpected token }
databomb.php:191 Uncaught TypeError: undefined is not a function

when using like this: src/marshaller/Graph ... src/marshaller/HTML works fine

**Comment by mlzummo** [comment]
GraphWidget.prototype.render.call(context, function (widget) {
                 if (callback) 
                     callback(widget);
                 }
             });

missing bracket if (callback) {

**Comment by GordonSmith** [comment]
@mlzummo Please re-review (fixed Graph issue).

**Comment by mlzummo** [comment]
looks good

**Pull request merged**
