### PR TITLE
Allow events across dashboards.

### PR DESCRIPTION
**Pull request by GordonSmith**
Add tabs to HTML Marshaller.

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@drealeed @mlzummo Please Review

**Comment by mlzummo** [comment]
@GordonSmith do you have a demo we can see of this in action?

**Comment by mlzummo** [comment]
is this going to effect commsDataLoaded function which uses the visualization array?

**Comment by GordonSmith** [comment]
http://rawgit.com/GordonSmith/Visualization/DDL_TABS/demos/marshaller/index.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20150826-101658&ResultName=leeddx_issue_381_filterviz_Comp_Ins002_DDL&HTML

**Comment by drealeed** [comment]
This looks good to me.

**Pull request merged**
