### PR TITLE
fix(pie): improved label placement handling

### LINKED ISSUE #2956: Pie chart tick labels overlap for smaller values

### PR DESCRIPTION
**Pull request by jbrundage**
Fixes #2956

Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

### CODE REVIEW

**Comment by jbrundage** [comment]
It looks good in many cases:
image

...but there are two edge cases that cause undesired behavior:
1.) Any overlapping label shifts towards the top to avoid overlap... occasionally resulting in this:
image

2.) When "height" is the limiting dimension the labels push beyond the edge:
image

**Comment by GordonSmith** [comment]
Nearly there!
1 - looks like the pie gets shrunk "after" the labels were positioned (looking at "P")?

**Comment by jbrundage** [comment]
@GordonSmith I've fixed the first issue and the "P" issue

The overlapping labels are sorted by their "top" value and then shifted towards the top by `n * maxLabelHeight` where `n` is the index of the label. It's working much better but this can cause a new type of overlap. See the pic below...

image

...the WWWWW slightly overlapped with the VVVVV, so it shifted upwards and now overlaps with XXXXX.

**Comment by jbrundage** [comment]
@GordonSmith I added:
- minOuterRadius
- vertical centering for the whole widget (based on the final positions of the labels)
- the widget based on the don't see any edge case issues now
- added calcSmallValueLabelHeight that approximates how much vertical space will be needed (and uses the approximation in calcOuterRadius to prevent edge case "2" from my initial comment)

image

**Comment by jbrundage** [comment]
I'm not seeing any edge case issues now

**Comment by jbrundage** [comment]
image

**Comment by GordonSmith** [comment]
I have started to review - but it is looking like a big improvement!

**Comment by GordonSmith** [comment]
* There should be no crossing lines.
* When the "small slices" are in the bottom right / left quadrant, then the labels should get pushed down not up

**Comment by jbrundage** [comment]
Closing in favor of #3054

**Pull request closed without merging**
