### PR TITLE
Add support for ES6/SystemsJS/JSPM

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage @mlzummo Please Review
Adds support for:
* SystemJS loader (similar to RequireJS)
* jspm (similar to npm and bower)
* es6

The upshot is that the following code now works:  https://github.com/hpcc-systems/Visualization/pull/1499/files#diff-79d484d30861ba39f0ffe501e46d6499 which is pretty sweet...

Note:  I haven't added all the config pieces to make it work from rawgit - but running / hosting local just works - you will need to do a:
```
npm install
jspm install
```
to get the ball rolling. 

Note II:  This doesn't replace our existing load / build / release mechanism - but adds an alternative one (with es6 support).

**Comment by mlzummo** [comment]
@GordonSmith ill look over this this week sometime, there is alot of changes and new stuff here

**Comment by GordonSmith** [comment]
Please re-submit PR for 1.14.0

**Comment by GordonSmith** [comment]
Closing in favor of:  https://github.com/hpcc-systems/Visualization/pull/1529

**Pull request closed without merging**
