### PR TITLE
feat: Add deck.gl

### PR DESCRIPTION
**Pull request by jbrundage**
@GordonSmith please review

Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

### CODE REVIEW

**Comment by jbrundage** [comment]
image

**Comment by jbrundage** [comment]
I'm not sure how the projection should be handled when layering this with GMap... When deck.gl uses the projected coordinates nothing renders. It needs the real lat/long and I guess it handles its own projection and GMap+deck.gl just need to sync their zoom/pan? Thoughts?

**Comment by jbrundage** [comment]
image

**Comment by GordonSmith** [comment]
It might be easier to get it working on a Choropleth first?

**Comment by GordonSmith** [comment]
Closing from main repository (if you want to issue a PR to my repo for further exploration please do).

**Pull request closed without merging**
