### PR TITLE
GH-1010 Adds AmChart - Gantt

### PR DESCRIPTION
**Pull request by mlzummo**
@GordonSmith @dtsnell4 @jbrundage - Please Review

the TODO's question marks could use some commenting and im waiting to here back from amcharts on how to handle the selection coloring

Adds AmChart - Gantt
Fixes GH-1010

Signed-off-by: Mathew Zummo <mzummo@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@dtsnell4, @jbrundage please review.  @mlzummo is there a demo link?

**Comment by mlzummo** [comment]
@GordonSmith - http://rawgit.com/mlzummo/Visualization/AMCHART_GANTT_3/demos/dermatology.html?src/amchart/Gantt

**Comment by dtsnell4** [comment]
Looks good to me

**Comment by jbrundage** [comment]
Looks good to me too. Though this chart type deserves more complex test data

**Pull request merged**
