### PR TITLE
GH-1469 Optionally allow clear to propagate

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes GH-1469

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo Please Review

**Comment by mlzummo** [comment]
it works but the selection gets cleared now it looks even though it "stays" in the event target widget

**Comment by GordonSmith** [comment]
That is why I made it optional, as this behavour isn't always wanted - say the Choro was a bar chart and say the selection no longer even existed in that bar chart...

**Comment by GordonSmith** [comment]
https://github.com/hpcc-systems/Visualization/issues/1485

**Pull request merged**
