### PR TITLE
GH-510 Add "time" support to Slider

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes GH-510

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo Please Review

**Comment by mlzummo** [comment]
Add click event place holder function?

**Comment by mlzummo** [comment]
(not sure if matters) but if you try to click back from time/time range to linear it doesn't update the slider back ...

**Comment by GordonSmith** [comment]
click is in IInput

**Comment by mlzummo** [comment]
click wasnt returning anything in the test, had to add slider.click ... should it have been echoing out to console?

**Comment by GordonSmith** [comment]
Fixed (and added console echo for click event).

**Pull request closed without merging**
