### PR TITLE
GH-1756 Icon enums not working

### PR DESCRIPTION
**Pull request by GordonSmith**
Requires https://github.com/hpcc-systems/HIPIE/issues/1796

Fixes GH-1756

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage, @mlzummo Please Review

**Comment by mlzummo** [comment]
code looks good, do we have a review link though?

**Comment by GordonSmith** [comment]
Its about to change again (some additional HIPIE tweaks, so I will leave this open until they are in sync.

**Comment by jchambers-ln** [comment]
Code looks good

**Comment by GordonSmith** [comment]
Updated for latest HIPIE - @jchambers-ln @mlzummo Please Rereview

**Comment by GordonSmith** [comment]
Closing in favor of:  https://github.com/hpcc-systems/Visualization/pull/1834 (requires a HIPIE 1.7 change)

**Pull request closed without merging**
