### PR TITLE
GH-1713 Optionally keep flyout forms open on submit

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes GH-1713

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage  @mlzummo @jchambers-ln Please Review

**Comment by jbrundage** [comment]
@GordonSmith Excellent! This looks good.

**Comment by jchambers-ln** [comment]
Looks good, do you want to leave the HACK: comment?

**Comment by GordonSmith** [comment]
@jchambers-ln yes - it is a big hack.

**Pull request merged**
