### PR TITLE
fix(TitleBar):  Select had incorrect "selected" value.

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

## Checklist:
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit message includes a "fixes" reference if appropriate.
  - [x] The commit is signed.
- [x] The change has been fully tested:
  - [ ] I have viewed all related gallery items
  - [ ] I have viewed all related dermatology items
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised new issues to address them separately

### CODE REVIEW

**Comment by GordonSmith** [comment]
Your change will fail in IE11

**Comment by jbrundage** [comment]
Shouldn't IE11 use the ES5 build?

**Comment by GordonSmith** [comment]
It does - but I didn't think typescript will transpile that?

**Comment by GordonSmith** [comment]
Property 'entries' does not exist on type 'ObjectConstructor'.

**Comment by jbrundage** [comment]
Ah okay, after a bit of searching it looks like folks are importing polyfills from `core-js` to add `Object.entries` support. It's probably not worth it.

**Pull request merged**
