### PR TITLE
Adds Theme Editor Widget

### PR DESCRIPTION
**Pull request by mlzummo**
@GordonSmith @jbrundage Please Review

Signed-off-by: Jay Brundage <jaman.brundage@lexisnexis.com>

### CODE REVIEW

**Comment by mlzummo** [comment]
There are some globals that are used ... is there away to set jslint to ignore em with some directive?

**Comment by mlzummo** [comment]
@GordonSmith @jbrundage 

we could ignore the errors or move the data into the themeditor object?
        /* jshint ignore:start */
        g_defaultSerials(idx);
        /* jshint ignore:end */

**Comment by GordonSmith** [comment]
Is there a rawgit demo of the theme editor on its own?

**Comment by mlzummo** [comment]
@GordonSmith ... no thats why i originally included everything in one PR .. should i merge everything into one PR again?

**Comment by GordonSmith** [comment]
@mlzummo / @jbrundage 
Question:  If the theme editor doesn't work as a standalone widget - then it should probably be moved out to the app folders?

**Comment by mlzummo** [comment]
closing in favor of pull #499

**Pull request closed without merging**
