### PR TITLE
GH-584 D3 Tooltip Widget

### PR DESCRIPTION
**Pull request by GordonSmith**
Add Tooltips to existing HPCC Charts

Fixes GH-584

Signed-off-by: <Dan.Snell@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage Please Review - this is a refactored version of Dans tooltip.  The tooltip is ugly at the moment, but I plan on unifying it and the legend once it pulled...

**Comment by GordonSmith** [comment]
Rebased on a better AbsoluteSurface - also can use SVG as the tooltip

**Comment by jbrundage** [comment]
Looks good to me

**Comment by mlzummo** [comment]
looks good

**Pull request merged**
