### PR TITLE
Added Legend widget

### PR DESCRIPTION
**Pull request by jbrundage**
@GordonSmith @mlzummo please review

Signed-off-by: Jay Brundage <jaman.brundage@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage I suspect we need a "click" event?

**Comment by jbrundage** [comment]
Yes, following the discussion in Jo's office regarding the importance of the Legend widget... maybe we should expose several types of click events?  (Alt+Click, Shift+Click, etc...)

**Comment by GordonSmith** [comment]
Can you rebase and reissue against candidate-1.0.0

**Comment by mlzummo** [comment]
closed, pulled via new branch: https://github.com/hpcc-systems/Visualization/pull/335

**Comment by mlzummo** [comment]
should close this PR

**Pull request closed without merging**
