### PR TITLE
DRAFT: Add HexBin.md with random data generator concept

### PR DESCRIPTION
**Pull request by jbrundage**
## Checklist:
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit message includes a "fixes" reference if appropriate.
  - [ ] The commit is signed.
- [ ] The change has been fully tested:
  - [ ] I have viewed all related gallery items
  - [ ] I have viewed all related dermatology items
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised new issues to address them separately

### CODE REVIEW

**Comment by jbrundage** [comment]
@GordonSmith ignore the files other than HexBin.md. What do you think about the "getData" function? We need some way to generate a large amount of data for charts like HexBin and Contour to effectively convey their usefulness.

**Comment by GordonSmith** [comment]
I don't see any documentation in `HexBin.md` apart from the sample code?

**Comment by jbrundage** [comment]
@GordonSmith right, the sample code is what I wanted to get your opinion on. Some widgets will need large amounts of data in order to properly demo their use. Does that `getData` logic seem straight forward enough for such cases?

**Comment by GordonSmith** [comment]
@jbrundage can you rebase?

**Pull request closed without merging**
