### PR TITLE
GH-662 Adds SelectionBag to Grid

### LINKED ISSUE #662: Add SelectionBag to GridLayout designMode

### PR DESCRIPTION
**Pull request by jbrundage**
SelectionBag is now utilized in layout/Grid to handle the selection of one or more Cells.

Fixes #662

@GordonSmith Please review

https://rawgit.com/jbrundage/Visualization/GridLayout_meets_SelectionBag/demos/dermatology.html?src/layout/Grid&designMode=true

Signed-off-by: Jay Brundage <jaman.brundage@lexisnexis.com>

### CODE REVIEW

**Comment by jbrundage** [comment]
@GordonSmith The failed build doesn't seem to be related to my changes

**Comment by GordonSmith** [comment]
@jbrundage:
1.  Multi select should only work with "ctrl" key pressed (it should toggle the clicked item on off and leave the rest as is).  Single click with no ctrl will select that item and deselect everything else.
2.  WHen more than 1 item is selected the property editor should switch to paramGrouping=By PAram mode.

**Comment by jbrundage** [comment]
@GordonSmith Check it out, did I get it right?

https://rawgit.com/jbrundage/Visualization/GridLayout_meets_SelectionBag/demos/dermatology.html?src/layout/Grid&designMode=true

**Comment by GordonSmith** [comment]
@jbrundage You need to reset the "By Param" to "By Widget" when <= 1 items are selected...  But looks good otherwise.

**Comment by jbrundage** [comment]
It does reset to "By Widget" when <= 1

**Comment by GordonSmith** [comment]
1. Multi Select
2. Change a property (color to red)
3. Select 1 item:
image

**Comment by jbrundage** [comment]
@GordonSmith I'm not sure how these lint issues were triggered...

**Comment by jbrundage** [comment]
Otherwise... I've fixed the "switch back to By Widget" issue.

**Comment by GordonSmith** [comment]
@jbrundage - One thing I find difficult is turning off the design mode as you only have access to it when nothing is selected...
How about if you click on the canvas it also de-selects?

**Comment by GordonSmith** [comment]
@jbrundage If you rebase on latest candidate-1.6.0 it will fix your lint issues.

**Comment by jbrundage** [comment]
@GordonSmith I believe this is ready to be merged

**Pull request merged**
