### PR TITLE
GH-991 Add better error reporting.

### PR DESCRIPTION
**Pull request by GordonSmith**
Added ES6 Promise/A+ Polyfill

Fixes GH-991

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@dtsnell, @mlzummo Please Review.

**Comment by mlzummo** [comment]
looks good, let me test on integration first

**Comment by jbrundage** [comment]
@GordonSmith It looks like ES6 Promises aren't supported in any IE browsers.

http://caniuse.com/#feat=promises

**Comment by GordonSmith** [comment]
@jbrundage it includes a Polyfill...

**Comment by jbrundage** [comment]
Ah, right... sounds good .then

**Comment by GordonSmith** [comment]
@mlzummo Once you get a chance to test with DSP I will pull?

**Comment by mlzummo** [comment]
@GordonSmith tested on DSP works well

**Pull request merged**
