### PR TITLE
Mkdocs2

### PR DESCRIPTION
**Pull request by mlzummo**

### CODE REVIEW

**Comment by mlzummo** [comment]
work in progress 
preview:

http://rawgit.com/mlzummo/Visualization/mkdocs2/visualization-mkdocs/site/Index/index.html

**Comment by mlzummo** [comment]
mkdocs also supports exporting to github as well so we can export these to the wiki... though i dont think they will look as good

**Comment by GordonSmith** [comment]
@mlzummo Needs rebase
@jbrundage @dtsnell4 Please Review

**Comment by GordonSmith** [comment]
@mlzummo if this is not for review please close.

**Pull request closed without merging**
