### PR TITLE
GH-1195 Popup Layout needs shrink to fit option

### PR DESCRIPTION
**Pull request by dtsnell4**
Adds shrinkWrap() parameter that resizes the popup around its content widget if it has an explicit size.
Also adds the centerPopup() parameter which will center the popup in its container, or in the window.

Fixes GH-1195

Signed-off-by: Dan Snell <Dan.Snell@lexisnexis.com>

### CODE REVIEW

**Comment by dtsnell4** [comment]
@GordonSmith @mlzummo @jbrundage Please review.

I targeted 10.0 because thats what I started with, but there is obviously to rush to get it into rc-2.

http://rawgit.com/dtsnell4/Visualization/GH-1195_Popup_Shrink/demos/dermatology.html?src/layout/Popup.shrink
http://rawgit.com/dtsnell4/Visualization/GH-1195_Popup_Shrink/demos/dermatology.html?src/layout/Popup.shrink2

**Comment by dtsnell4** [comment]
@mlzummo I made some significant changes to this based on the issues you were having with it earlier.  I did not alter any of the original parameters, so it should not break anything, but let me know how it works out.

**Comment by mlzummo** [comment]
this looks good, however we still need to figure out a way for forms to take up minimal space without defining a size

**Comment by GordonSmith** [comment]
@mlzummo @jbrundage Please (re)Review

**Comment by jbrundage** [comment]
@GordonSmith Looks good to me

**Comment by jbrundage** [comment]
@mlzummo I created an issue for the form requirement you mentioned #1317

**Comment by mlzummo** [comment]
looks good to me

**Comment by jbrundage** [comment]
@GordonSmith This is ready to be pulled

**Pull request merged**
