### PR TITLE
AbsoluteSurface Fixes

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo, @jbrundage Please Review

**Comment by mlzummo** [comment]
@GordonSmith do you have a rawgit link?

**Comment by GordonSmith** [comment]
@mlzummo I corrected the above link.

**Comment by mlzummo** [comment]
the widgets keeps popping in and out of the foreground like its z-index is being toggled? is it suppose to do that?

**Comment by jbrundage** [comment]
This looks intentional. The testData randomly sets the z-index every three seconds.

https://github.com/GordonSmith/Visualization/blob/ABS_SURFACE_FIXES/src/layout/Layered.js#L29-L37

Looks good to me.

**Comment by GordonSmith** [comment]
Yes it is intentional

**Pull request merged**
