### PR TITLE
GH-2065 Add column level clicking support

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes GH-2065

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jchambers-ln @drealeed Please Review

**Comment by drealeed** [comment]
Gordon,  I wanted to check your changes with the test wu I sent yesterday. But the link http://rawgit.com/GordonSmith/Visualization/GH-2065-ColClick/apps/legacyDash.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20161207-112811&ResultName=issue_1727_colselect_Comp_Ins003_DDL isn't working. Is this the correct link to test?

**Comment by drealeed** [comment]
The clicking feature looks good. i did notice an unrelated bug--the column spacing changes when the row is clicked.

**Comment by GordonSmith** [comment]
Known and fixed issue (waiting on review):  https://github.com/hpcc-systems/Visualization/pull/2132

**Pull request merged**
