### PR TITLE
Widget Resize Tweaks

### PR DESCRIPTION
**Pull request by GordonSmith**
Refactor and improve widget resizing, specifically the HTML Widget.

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@dineshshetye @jbrundage Please Review

**Comment by jbrundage** [comment]
I would think clientWidth and clientHeight should be contentWidth and contentHeight?  Otherwise, looks good

**Comment by GordonSmith** [comment]
"clientWidth/Height" - I am using those words because they match:  https://developer.mozilla.org/en-US/docs/Web/API/Element/clientHeight

**Comment by GordonSmith** [comment]
The overlay size should always match the SVG size and scale.  In general none of our widgets should need a scrollbar - with the current exception of Table  + Grid Layout when set to "width" mode.

The change is explicitly setting it that way - so in future if you write a widget that should allow scrollbars it will need to change the default overlay (like Table is doing).

**Pull request merged**
