### PR TITLE
GH-537 AmChart Click Events

### LINKED ISSUE #537: amcharts click events need to be added (read notes)

### PR DESCRIPTION
**Pull request by mlzummo**
@GordonSmith @drealeed @dtsnell4 @jbrundage 

Please Review

---

Adds click event to AmCharts

Fixes #537

Signed-off-by: Mathew Zummo <mzummo@gmail.com>

### CODE REVIEW

**Comment by mlzummo** [comment]
http://rawgit.com/mlzummo/Visualization/AMCHARTS_EVENTS/demos/dermatology.html?src/amchart/Bar

http://rawgit.com/mlzummo/Visualization/AMCHARTS_EVENTS/demos/dermatology.html?src/amchart/Funnel

**Comment by jbrundage** [comment]
Doesn't seem to work for Polar:
http://rawgit.com/mlzummo/Visualization/AMCHARTS_EVENTS/demos/dermatology.html?src/amchart/Polar

Also, Funnel and Pyramid wedges slide to the right by 30px when they're clicked, as if they're 'selected' wedges. This is their default action when clicked and we should be able to control this via publish params (should be treated as a separate issue I suppose).

**Comment by mlzummo** [comment]
need to add polar chart

**Comment by GordonSmith** [comment]
Looks fine.  Can you retarget to candidate-1.4.2 (or is master more appropriate).

Also in the future can you make the commit messages more like this "shape":  as per https://github.com/hpcc-systems/HPCC-Platform/wiki/Git-commit-message-guidelines

```
GH-537 AM Chart Click Events

Add click events to various AM Charts

Fixes GH-537 

Signed-off-by: Mathew Zummo <mzummo@gmail.com>
```

**Comment by mlzummo** [comment]
closing targeting 1.4.2

**Pull request closed without merging**
