### PR TITLE
GH-1063 Fixes AmChart & HPCC X-Axis Time

### PR DESCRIPTION
**Pull request by mlzummo**
@GordonSmith @dtsnell4 @jbrundage Please Review

Question1 - does the sorting need to be applied to the Y Axis and is the data index 1 or 0 on that if so?
Question2 - does this need to be applied to C3 and Google?

Fixes AmChart & HPCC X-Axis Time
Fixes GH-1063

Signed-off-by: Mathew Zummo <mzummo@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
1.  I am not sure Sorting the Y axis makes any sense?
2. In HIPIE the user has the ability to specify the sort order, which is why I haven't (to date) manually sorted the data internally in the widgets.

**Comment by mlzummo** [comment]
hmm ok thats food for thought

**Comment by dtsnell4** [comment]
Looks good to me

**Comment by mlzummo** [comment]
@GordonSmith @jbrundage - Please Review

**Comment by mlzummo** [comment]
@GordonSmith bump

**Pull request merged**
