### PR TITLE
Add Databomb Support to Graph Marshaller

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@gurux @jbrundage Please Review

**Comment by jbrundage** [comment]
Testing Databomb results in an error: "undefined is not a function" it's referring to Graph().ddl_url

https://rawgit.com/GordonSmith/Visualization/b5b39eba023a635e867b60d43e8f6dd5de41104f/demos/dashboard/databomb.html

**Comment by GordonSmith** [comment]
Sorry, the test page was using the HTML and not the Graph marshaller - fixed now:  http://rawgit.com/GordonSmith/Visualization/DATABOMB/demos/dashboard/databomb.html

**Comment by jbrundage** [comment]
Looks good

**Pull request merged**
