### PR TITLE
GH-890 Pagination + Narrow Space

### PR DESCRIPTION
**Pull request by dtsnell4**
Adds CSS so that the paginator does not wrap to another line.
Also added checks for fixedSize() param so the size is not set to 0.

Fixes GH-890
Fixes GH-1090

Signed-off-by: Dan Snell <Dan.Snell@lexisnexis.com>

### CODE REVIEW

**Comment by dtsnell4** [comment]
@GordonSmith @jbrundage @mlzummo Please review

This adds css that prevents the paginator from wrapping.  

At that point I believe it should be up to the developer, if necessary, to add their own css for font, padding, etc. to make the paginator itself smaller.  I got it to look like like with a few changes:

paginator

Additionally, there are really two paginators there.  The number input in the second one has a spin button to scroll through the page numbers, its really all that is necessary.  Dev can just hide the first one with css.

**Comment by dtsnell4** [comment]
@GordonSmith @mlzummo @jbrundage Don't bother reviewing, paginator stopped working, need to fix.

**Comment by dtsnell4** [comment]
@GordonSmith @mlzummo @jbrundage Fixed, please review (note above comment)

**Comment by dtsnell4** [comment]
http://rawgit.com/dtsnell4/Visualization/GH-890_Table_Narrow_Pagination/demos/dermatology.html?src/other/Table

**Comment by GordonSmith** [comment]
@mlzummo Please Review

**Comment by mlzummo** [comment]
looks good

**Pull request merged**
