### PR TITLE
GH-429 Surface Right/Bottom is getting clipped

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes GH-429

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo Please Review

**Comment by mlzummo** [comment]
looks ok, but would like @jbrundage to take a look at this as well

**Comment by GordonSmith** [comment]
(fixed linting issue)

**Comment by jbrundage** [comment]
Looks ok

**Pull request merged**
