### PR TITLE
Fix sizing of HTML Widget in SVG Widget.

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage Please Review.
Also I thought you fixed this one specifically:  http://rawgit.com/GordonSmith/Visualization/FIX_SIZE/test/runner_rawgit.html?src/layout/Border

**Comment by jbrundage** [comment]
Regarding the Border layout within the SVG container:
This FIX_SIZE branch doesn't contain the changes to src/layout/Border.js from this PR https://github.com/GordonSmith/Visualization/pull/36/files

**Comment by GordonSmith** [comment]
@jbrundage I know - this fix was for a different (more general) issue.  Your going to issue a PR for your fix at some point.

**Comment by dtsnell4** [comment]
@GordonSmith My latest PR should fix the table issues, other than that it all looks good to me.

**Pull request merged**
