### PR TITLE
Adds Zebra Table Color PP

### PR DESCRIPTION
**Pull request by mlzummo**
Fixes GH-743

Signed-off-by: Mathew Zummo <mzummo@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage @dtsnell4 Please review - I thought there was a 100% CSS fix for this?

**Comment by mlzummo** [comment]
you cant do it with CSS cause PP params overwrite the css

**Comment by mlzummo** [comment]
@GordonSmith Also will not bode well with themeing of the table...

**Comment by mlzummo** [comment]
@GordonSmith updated with css in addition to PP and @jbrundage for the second css option as well in the .css file commented out

**Comment by GordonSmith** [comment]
Closing in favor of:  https://github.com/hpcc-systems/Visualization/pull/935

**Pull request closed without merging**
