### PR TITLE
Table Widget Fixed First Column

### PR DESCRIPTION
**Pull request by dtsnell4**
Fixes a bug where the the table header disappears when the first column is turned off.

Signed-off-by: Dan Snell <Dan.Snell@lexisnexis.com>

### CODE REVIEW

**Comment by dtsnell4** [comment]
@GordonSmith Not sure what happened there.

**Comment by GordonSmith** [comment]
@dtsnell4 - the commit message and the changes don't seem to match?

**Comment by dtsnell4** [comment]
@GordonSmith fixed commit message

**Comment by jbrundage** [comment]
For some reason... this table isn't populating cells with data if the value isn't a string.

https://rawgit.com/dtsnell4/Visualization/Table_Widget_Fixed_Column2/demos/dermatology.html?src/other/Table

**Comment by jbrundage** [comment]
I just realized this was my doing... with a recent commit. I'll create a separate issue and PR with the fix.

**Pull request merged**
