### PR TITLE
GH-713 Fixes click event on Slider play

### PR DESCRIPTION
**Pull request by anmoljagetia**
Fixes GH-713 (#713)
Signed-off-by: Anmol Jagetia <anmoljagetia@gmail.com>

### CODE REVIEW

**Comment by anmoljagetia** [comment]
@GordonSmith @buunguyen Please review!

**Comment by buunguyen** [comment]
Question: is there a difference between `context.click()` and `context._click()`? Also not sure where is the latter defined?

**Comment by GordonSmith** [comment]
Yes one works and the doesn't

**Comment by buunguyen** [comment]
:-). Just checked the [source of the slider](http://rawgit.com/GordonSmith/Visualization/COMMS_DEMO/src/form/Slider.js) used in Rugby demo again, there's a separate `_click()` method that calls to `click()`. I guess @anmoljagetia can use the same mechanism.

**Comment by anmoljagetia** [comment]
I just saw the error, and realised that the new function is itself missing. Should I also refactor [these lines](https://github.com/anmoljagetia/Visualization/blob/sliderClickFix/src/form/Slider.js#L334-L341) to use the new function ?

**Comment by buunguyen** [comment]
@anmoljagetia I would say yes unless Gordon thinks otherwise. The Rugby slider does that.

**Comment by GordonSmith** [comment]
Resolved by: https://github.com/hpcc-systems/Visualization/pull/716

**Pull request closed without merging**
