### PR TITLE
Graph Annotations

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo Please Review

**Comment by mlzummo** [comment]
should we have put/pass a version string for the button Annotation code? J/Dan implemented the form input widget to render in a surface which looked nice for a demo, not 100% sure how it would work in the long run but would allow even more customization from the looks of it...

**Comment by GordonSmith** [comment]
Not sure I follow?  These annotations are on the GraphVertex?

**Comment by mlzummo** [comment]
your right i was looking at this end of day, and was seeing words similar to what I had in the surface button annotations so i jumped the gun a bit...

**Comment by mlzummo** [comment]
looks good, is there a way to test this at the moment?

**Comment by GordonSmith** [comment]
Rename testData2 to testData and open src/marshaller/HTML in dermatology

**Pull request merged**
