### PR TITLE
Publish properties for text, faChar, textbox, shape, icon and Vertex

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage @mlzummo Please Review - also note the new "optional" parameter for Publish.

**Comment by jbrundage** [comment]
This new '_enable' feature will be handy.  Alternatively we may want to rethink the idea of publish arguments.  

If '.publish()' simply expects one object argument it would give us the flexibility of adding enhancements to the publish feature.  For example... grouping publish parameters.  Thoughts?

**Comment by GordonSmith** [comment]
I have done away with "_enable" in a latter pull request...  Its not actually needed...

**Comment by GordonSmith** [comment]
Thats what the "ext" is at the end for adding "other arguments" I did toy with doing it the way you suggested, but I felt it made the code to hard to scan...

So now you can have:  publish("prop", 22, "integer", "My Super Prop", null, {attr: "a", attr: "b"});

**Comment by mlzummo** [comment]
looks good, ill be working with these widgets a little more over the next few days so i'll let you know if these changes cause any probs

**Comment by GordonSmith** [comment]
Rebased for pull.

**Pull request merged**
