### PR TITLE
GH-1118 Choro + Array of Weights

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes GH-1118

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo Please Review:

http://rawgit.com/GordonSmith/Visualization/GH-1118/demos/marshaller/index.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20151030-102448&ResultName=lrenn_choroweight_Comp_Ins002_DDL

http://rawgit.com/GordonSmith/Visualization/GH-1118/demos/marshaller/index.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20151030-103401&ResultName=lrenn_choroweight_Comp_Ins002_DDL

**Comment by mlzummo** [comment]
i was expecting a choropleth in the examples?

**Comment by GordonSmith** [comment]
Once we have a choro that can display dual weights we will use them - this is so that we can handle the new DDL format.

**Comment by mlzummo** [comment]
looks good

**Pull request merged**
