### PR TITLE
Allow inputs to be placed side by side.

### PR DESCRIPTION
**Pull request by GordonSmith**
Add option to drop empty fields from values() call.

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage Please Review

**Comment by jbrundage** [comment]
Looks good, but the "Button Test:" label cell is unnaturally wide in this example. Maybe we should force the label cells to consume the least amount of space possible?
https://rawgit.com/GordonSmith/Visualization/FORM_LAYOUT/demos/dermatology.html?src/form/Form

**Comment by GordonSmith** [comment]
@jbrundage Sounds good - how?

**Comment by GordonSmith** [comment]
Note:  Serialization test is not working...

**Comment by GordonSmith** [comment]
@jbrundage Please re-review (I added a new common/WidgetArray.js to fix the serialization issue).
Also I think we expanding the prompts + inputs correctly (inpputs class have a width of 100%), its just in this example none of the three inputs have any sensible way to expand...

**Comment by jbrundage** [comment]
The Form table isn't resizing itself when its container is resized.

**Comment by jbrundage** [comment]
The 'Button Test:' cell width is so wide that it's awkwardly far from the input it's describing.  Maybe we could wrap these labels in a <span> and use .getBoundingClientRect().width on all of the label spans to determine how wide the label cells should be (setting each label cell width to the width of the widest label cell span for each column).

**Comment by jbrundage** [comment]
Looks good

**Pull request merged**
