### PR TITLE
feat: Widget parameters as constructor arg

### PR DESCRIPTION
**Pull request by jbrundage**
Auto-render if any parameters are specified in this way

Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
What is the motivation for this?

**Comment by GordonSmith** [comment]
Targeting wrong branch for PR

**Comment by jbrundage** [comment]
What do you think about this concept? We aren't currently using the constructor arguments for anything so I threw this PR out there as a conversation starter. Passing the publish parameter values as options in this way would actually simplify the code generation process. Thoughts?

**Comment by GordonSmith** [comment]
I am going to close this for now as would need to think about it (for the 3.x time frame) - open an issue for the discussion.

**Pull request closed without merging**
