### PR TITLE
Refactors AmCharts Scatter

### PR DESCRIPTION
**Pull request by mlzummo**
@GordonSmith @jbrundage Please Review

Signed-off-by: Mathew Zummo <mzummo@gmail.com>

### CODE REVIEW

**Comment by mlzummo** [comment]
the following URLs allow you to test ordinal/linear across bubble and scatter modes

http://rawgit.com/mlzummo/Visualization/AMCHARTS_SCATTER_REFACTOR/demos/dermatology.html?src/amchart/Scatter&chartMode=bubble

http://rawgit.com/mlzummo/Visualization/AMCHARTS_SCATTER_REFACTOR/demos/dermatology.html?src/amchart/Scatter&chartMode=scatter

http://rawgit.com/mlzummo/Visualization/AMCHARTS_SCATTER_REFACTOR/demos/dermatology.html?src/amchart/Scatter&xAxisType=linear&chartMode=scatter&sampleData=linear

http://rawgit.com/mlzummo/Visualization/AMCHARTS_SCATTER_REFACTOR/demos/dermatology.html?src/amchart/Scatter&xAxisType=linear&chartMode=bubble&sampleData=linear

**Comment by mlzummo** [comment]
the label function is getting passed slightly diff vals in the unitTest Vs dermatology and test pages and i am not sure why

**Comment by jbrundage** [comment]
If you call validateData before you call validateNow it will fix your labelFunction issue.

https://github.com/mlzummo/Visualization/blob/AMCHARTS_SCATTER_REFACTOR/src/amchart/Scatter.js#L71-L72

**Comment by jbrundage** [comment]
How can I display this data set with amchart/Scatter?
**X-Axis** placement represents some numeric statistic
**Y-Axis** placement represents another numeric statistic
**Color** of the data point represents category
**Size** of the data point represents another numeric statistic

**Comment by mlzummo** [comment]
there isnt a category color right now, and the data shapes i suspect will need to be modified to account for coloring in a category.

as for the rest just select bubble chart and xAxisLinear

**Comment by jbrundage** [comment]
I think category color is important for this type of chart.

When I select xAxisType=linear, chartMode=bubble, and sampleData=linear:
http://rawgit.com/mlzummo/Visualization/AMCHARTS_SCATTER_REFACTOR/demos/dermatology.html?src/amchart/Scatter&xAxisType=linear&chartMode=bubble&sampleData=linear

The size of the bubble doesn't seem to correlate to the sizes here:
https://github.com/hpcc-systems/Visualization/pull/718/files#diff-dbb58d4e35345177148d50bd197c07a2R96

**Comment by mlzummo** [comment]
@GordonSmith for ordinal we use INDData shape whats the correct method to incorporate ordinal with category as described above?

**Comment by mlzummo** [comment]
reissueing

**Pull request closed without merging**
