### PR TITLE
GH-1045 GMap Unit Test Fix

### PR DESCRIPTION
**Pull request by mlzummo**
@GordonSmith Please Review

Signed-off-by: Mathew Zummo <mzummo@gmail.com>

### CODE REVIEW

**Comment by mlzummo** [comment]
@GordonSmith Does this need to be down merged into 1.6.8?

**Comment by GordonSmith** [comment]
Seems to break:  http://rawgit.com/hpcc-systems/Visualization/master/demos/dermatology.html?src/map/GMap.heat and http://rawgit.com/hpcc-systems/Visualization/master/demos/dermatology.html?src/map/GMap.graph

**Comment by mlzummo** [comment]
the callback isnt calling back ... testing some other stuff

**Comment by mlzummo** [comment]
@GordonSmith i am able to replicate this / travis issues on a linux box (VM)

**Pull request closed without merging**
