### PR TITLE
GH-1101 Table column totals

### PR DESCRIPTION
**Pull request by dtsnell4**
Adds params to sum total the contents of a numeric column.

Fixes GH-1101

Signed-off-by: Dan Snell <Dan.Snell@lexisnexis.com>

### CODE REVIEW

**Comment by dtsnell4** [comment]
@GordonSmith @mlzummo @jbrundage Please review

http://rawgit.com/dtsnell4/Visualization/GH-1101_Table_Column_Totals/demos/dermatology.html?src/other/Table.totalled

**Comment by mlzummo** [comment]
looks good

**Comment by GordonSmith** [comment]
1 - I think visually the totals are not obviously totals enough - they need to look more different - maybe they should not have a grid around them?
2 - They only total the current page when pagination is on (is this a feature or an issue?)

**Comment by dtsnell4** [comment]
1.  I would expect the user to be adding their own CSS to differentiate it, but I can certainly add a default look.
2.  After speaking with Matt and DSP, from what we gathered it is a feature.

**Comment by dtsnell4** [comment]
@GordonSmith updated based on comments, with the exception of #1 above, as I understand it, it is correct.

**Pull request merged**
