### PR TITLE
Fixes #560 Marshaller Sorting of table

### PR DESCRIPTION
**Pull request by mlzummo**
@GordonSmith @drealeed @jbrundage @dtsnell4 

Please Review

http://rawgit.com/mlzummo/Visualization/SORTING_EXP/demos/marshaller/index.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20150724-092702&ResultName=shetyedv_dash072401_Comp_Ins004_DDL

http://rawgit.com/mlzummo/Visualization/SORTING_EXP/demos/marshaller/index.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20150724-095400&ResultName=leeddx_sorttest_Comp_Ins007_DDL

Signed-off-by: Mathew Zummo <mzummo@gmail.com>

### CODE REVIEW

**Comment by mlzummo** [comment]
http://rawgit.com/mlzummo/Visualization/GH-600-MARSHALLER_SORTING_FIX/demos/marshaller/index.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20150724-092702&ResultName=shetyedv_dash072401_Comp_Ins004_DDL

http://rawgit.com/mlzummo/Visualization/GH-600-MARSHALLER_SORTING_FIX/demos/marshaller/index.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20150724-095400&ResultName=leeddx_sorttest_Comp_Ins007_DDL

**Comment by mlzummo** [comment]
remove the extra form auto submit code and default value that bled over

**Comment by mlzummo** [comment]
@GordonSmith Please Re-Review

**Comment by GordonSmith** [comment]
I was thinking if we pushed this higher up the tech stack to where the JSON data object is first "seen".
If we converted any strings containing numbers to actual numbers then it would also fix the google data issue we had previously?

**Comment by mlzummo** [comment]
@GordonSmith we can't convert something like S700_A52 to a number, i'm not sure I follow. Do you want to go ahead and use this table sorting algo? what google data issue are you referring to specifically?

**Comment by GordonSmith** [comment]
IMO "S700_A52" Should be sorted as a string,  I am referring to the issue that "7" > "111" but 7 < 111

**Comment by mlzummo** [comment]
@GordonSmith yea i played with a previous algo where i did a regex test to test if all digits were numbers and then did Number(a) ... we could still do that higher up the stack... I hope we still plan on using this sorting algo though i put a lot of time into finding one that works flawless and with all the test conditions i could find ... this sorts as most people would want to have sorting as well.

**Comment by GordonSmith** [comment]
Closing in favor of:  https://github.com/hpcc-systems/Visualization/pull/641

**Pull request closed without merging**
