### PR TITLE
GH-806 Surface menu overlay issue

### PR DESCRIPTION
**Pull request by GordonSmith**
Note:  C3 Legends are not being hidden

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo Please Review - this is the general fix - but C3 Legends get created in the global DOM so they don't get hidden with this fix...

**Comment by mlzummo** [comment]
@GordonSmith this doesn't fix the underlying issue as far as i can see? if this does fix other issue's open a new issue and reference that?

**Comment by GordonSmith** [comment]
I didn't add the "fixes gh-xxx" to the commit comment for this very reason - but this PR is very much related.

**Comment by mlzummo** [comment]
code looks good, are there still alot of areas where we are not calling the PP function method?

**Comment by GordonSmith** [comment]
I didn't think there where any left...

**Pull request merged**
