### PR TITLE
Addition of Brasil to Choropleth roster

### PR DESCRIPTION
**Pull request by dwheelock**
Added BR.json to the list of region files under map/TopoJSON, and updated TopoJSONChoropleth.js to include BR as a known region.

### CODE REVIEW

**Comment by GordonSmith** [comment]
@dwheelock looks good - did you want it based on 1.16.x or 1.20.x (your PR was against 1.16, but your code was based on 1.20)?

**Comment by GordonSmith** [comment]
Also I thought you wanted higher resolution than states?

**Comment by dwheelock** [comment]
Gordon, sorry about the version -- it has been a while since I GitHub'ed.  I forked from 1.20, but in reading your e-mail about the update process you said to issue the pull request against 1.16.x.  Would you prefer I issue it to 1.20 instead?

re: higher resolution, yes.  I was going to try to put together a map based on the first two digits of the postal code, but I couldn't find anything easily available so I just grabbed what I could.  Maybe someday I'll take the time to update this json file to include the postal code arcs.

**Comment by GordonSmith** [comment]
Closing in favor of:  https://github.com/hpcc-systems/Visualization/pull/2542 (rebased onto 1.16.x)

**Comment by GordonSmith** [comment]
FYI - merged to 1.16, 1.18, 1.20, 2.x

**Pull request closed without merging**
