### PR TITLE
Issue #518: Tabbed Content, basic implementation.

### PR DESCRIPTION
**Pull request by dtsnell4**
Basic layout of tabs and content panels

Signed-off-by: Dan Snell <Dan.Snell@lexisnexis.com>

### CODE REVIEW

**Comment by dtsnell4** [comment]
@GordonSmith I have no idea why this keeps failing, its complaining it can't find a file because it has a double 'src/src' in the path which is understandable.  But no where in my code do I have that directory doubled like that.  I'm at a loss.  It passes on my local environment. Same with PR #544

**Comment by GordonSmith** [comment]
I think you should restructure it so that the user can add/remove tabs at runtime - as it stands you must add all your tabs before the first call to render.

Also I don't think the serialization test in dermatology is going to work - for that you would probably need to change your annotations array to be a WidgetArray.

**Comment by dtsnell4** [comment]
@GordonSmith Is there an example of something using a Widget Array?

**Comment by GordonSmith** [comment]
The Grid uses one:      
```
Grid.prototype.publish("content", [], "widgetArray", "widgets",null,{tags:['Private']});
```

**Comment by dtsnell4** [comment]
@GordonSmith @mlzummo @jbrundage Please review

I changed it to use the widget array as you suggested (Todo: create a removeTab() method).  It works fine in Dermatology, however it still errors on the serialization test.  I think I know why, but I don't quite know what to do about it.  I need to look into how Persist and the Property editor work.  In the meantime if anyone sees what I am doing wrong or has any suggestions, please let me know.

**Pull request closed without merging**
