### PR TITLE
GH-928 Add alternate line backgrounds to Table

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes GH-928

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage @dtsnell4 Please Review

**Comment by dtsnell4** [comment]
@GordonSmith when showHeader is false, but fixedColumn is still true, when you click on a row to highlight/select it, the wrong fixed column row gets highlighted.

**Comment by GordonSmith** [comment]
I hadn't noticed that - but I see the same thing in master:  http://rawgit.com/hpcc-systems/Visualization/master/demos/dermatology.html?src/other/Table
So its an existing bug (can you open an issue for that?)

**Comment by GordonSmith** [comment]
@jbrundage @dtsnell4 bump

**Comment by dtsnell4** [comment]
Sorry, other than the issue I pointed out its good to go.

**Pull request merged**
