### PR TITLE
Adds Theme Editor

### PR DESCRIPTION
**Pull request by jbrundage**
@GordonSmith Please Review .. did not include bower components in PR... you will need to do bower install from demos/ after downloading locally

Signed-off-by: Jaman Brundage <Jaman.Brundage@lexisnexis.com>

### CODE REVIEW

**Comment by mlzummo** [comment]
final version will use bower_components dir like Playground

**Comment by GordonSmith** [comment]
Can you move this to a subfolder in apps.

**Comment by GordonSmith** [comment]
Can you move the widget src changes into a separate PR?

**Comment by GordonSmith** [comment]
(Travis is failing also)

**Pull request closed without merging**
