### PR TITLE
MultiChart not resizing correctly

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage Please Review

**Comment by mlzummo** [comment]
@Gor does this have an isssue#?

**Comment by GordonSmith** [comment]
@mlzummo no, just found it and fixed it.

**Comment by mlzummo** [comment]
looks good to me

**Pull request merged**
