### PR TITLE
Add support for WsWorkunits/WUGetStats

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo, @jbrundage Please Review

**Comment by GordonSmith** [comment]
@mlzummo, @jbrundage Please Review

**Comment by GordonSmith** [comment]
Bump:  @mlzummo, @jbrundage Please Review

**Comment by jbrundage** [comment]
Looks good (syntactically).  I'm not sure what this portion of code does.

**Comment by GordonSmith** [comment]
(FYI Its a wrapper for the ESP Stats)

**Pull request merged**
