### PR TITLE
Tweaks for HPCC ECL Watch

### PR DESCRIPTION
**Pull request by GordonSmith**
Text Widget would not show duplicate lines.
Text Widget would not maintain correct order.
Added tooltip support to:
* Shape, TextBox, Vertex, Edge

Added selection support for edges.
Reversed scroll wheel and ctrl+scroll wheel behaviour.

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo, @dtsnell4 Please Review

**Comment by dtsnell4** [comment]
Looks goods to me.

**Comment by mlzummo** [comment]
GHs diff still leakes much to be desired ...

**Comment by GordonSmith** [comment]
Weird - if you add ?w=1 to the URL it helps a lot:
https://github.com/hpcc-systems/Visualization/pull/1227/files?w=1

**Pull request merged**
