### PR TITLE
WIP:  First cut at a docs engine

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

## Checklist:
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit message includes a "fixes" reference if appropriate.
  - [ ] The commit is signed.
- [ ] The change has been fully tested:
  - [ ] I have viewed all related gallery items
  - [ ] I have viewed all related dermatology items
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised new issues to address them separately

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage can you take this for a spin and see what you think?
```
cd website
npm install
npm run start
```

**Comment by GordonSmith** [comment]
This is what it looks like in gh-pages:  http://gordonsmith.github.io/Visualization/

**Comment by jbrundage** [comment]
Looks good, but how should we display the publish parameters for each package's widgets?
Maybe in the package left-nav collapsible? 
image

**Comment by GordonSmith** [comment]
No - the LHS will have the list of widgets in a given package - but the PP and methos will appear on the RHS for a given widget (each item on the LHS is a separate file as well).

**Pull request closed without merging**
