### PR TITLE
Table Widget Fixed First Column

### PR DESCRIPTION
**Pull request by dtsnell4**
Added fixedColumns as publish parameter so user can choose either fixed first column, fixed header, or both.

Signed-off-by: Dan Snell <Dan.Snell@lexisnexis.com>

### CODE REVIEW

**Comment by dtsnell4** [comment]
@GordonSmith @mlzummo @jbrundage  Please review

**Comment by GordonSmith** [comment]
@dtsnell4 You can reissue this against 1.6.0?

**Comment by GordonSmith** [comment]
Turning fixedHeader on and off loses it.

**Comment by dtsnell4** [comment]
@GordonSmith Sorry, it took me a bit to figure this out because it depended on the order you turned off the column and header.  One way was fine (apparently the way I always did it) and the other way wasn't.  Thanks for catching it. PR is updated.

**Comment by GordonSmith** [comment]
Can you re-issue against 1.6.0?

**Comment by GordonSmith** [comment]
Closing in favor of:  https://github.com/hpcc-systems/Visualization/pull/800

**Pull request closed without merging**
