### PR TITLE
GH-1936 WUID Dashboards duplicate result fetches

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes GH-1936

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jchambers-ln Please Review

**Comment by jchambers-ln** [comment]
@GordonSmith you may want to give this a once over yourself It may just be Git diff engine but it is listing un changed lines a changed.

The actual change looks good from what I could tell.

**Comment by GordonSmith** [comment]
Its marking them as changed due to indentation add "?w=1" to the url to see the actual changes:
https://github.com/hpcc-systems/Visualization/pull/1937/files?w=1

**Comment by jchambers-ln** [comment]
@GordonSmith that is a useful feature looks good to me.

**Pull request merged**
