### PR TITLE
GH-1794 MissingData + Aggregates

### PR DESCRIPTION
**Pull request by GordonSmith**
Ignore missing data and aggregate functions.

Fixes GH-1794-MissingDataFunc

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jchambers-ln, @hamiltwp Please Review

**Comment by mlzummo** [comment]
@GordonSmith this code right here is going to have direct impact on fixing current issue i see in candidate 1.14.x however this doesnt fix the issue we are going to need more code around this?

**Comment by jchambers-ln** [comment]
looks good, however I don't know your code well enough here to know if it properly fixes everything

**Comment by jchambers-ln** [comment]
I made the change locally and it solved the choropleth issue, so I think it is good.

**Comment by GordonSmith** [comment]
The underlying issue, is that roxie can omit fields from the response when there is no data (rather than returning empty fields.  We added code which can optionally display ***MISSING*** in the table widget, but in this scenario the field was used as part of an aggregate hence the extra test.

**Pull request merged**
