### PR TITLE
feat(3D): Add Treemap3D.ts

### PR DESCRIPTION
**Pull request by jbrundage**
Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

### CODE REVIEW

**Comment by jbrundage** [comment]
image

**Comment by jbrundage** [comment]
image

**Comment by jbrundage** [comment]
This code can easily be modified to use THREEjs and the yaw/pan drag/zoom controls can be reused for all 3d charts added in the near future. Thoughts?

**Comment by GordonSmith** [comment]
@jbrundage Will this be able to support selection and clicking?

**Comment by jbrundage** [comment]
@GordonSmith yes, if it's ported to THREEjs (should be possible without major changes)

**Comment by GordonSmith** [comment]
@jbrundage I suspect we need to park this for now as I won't be able to pull until it has selection support.

**Pull request closed without merging**
