### PR TITLE
GH-542 Fixed table header and first column

### PR DESCRIPTION
**Pull request by GordonSmith**
Adds functionality for a fixed table header and fixed first column for the table widget.

Fixes GH-542

Signed-off-by: Dan Snell <dan.snell@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage, @mlzummo this Dans table header code with some fixes (still not perfect) can you have a play and let me know if we should pull it?  
http://rawgit.com/GordonSmith/Visualization/Table_Widget_Fixed_Header_542/demos/dermatology.html?src/other/Table

**Comment by jbrundage** [comment]
Ideally it should pull the styles for the fixed header/first-column from the table rather than from CSS.

Nothing seems to be broken per se... though enhancements could be added later. 

I suggest pulling it.

**Comment by mlzummo** [comment]
i second pulling, however does this issue still exist with this version?

https://github.com/hpcc-systems/Visualization/issues/738

**Comment by GordonSmith** [comment]
@jbrundage I am kind of at the stage with it where it works as was written - my main change was moving the different parts inside a root div, so it worked ok in SVG Surface and some minor tidy ups to help me understand the code. If I was to carry on I would probably end up re-structuring it to be more D3 like. 
@mlzummo Its better, but not perfect (it scrolls with the HScroll bar).

**Pull request merged**
