### PR TITLE
GH-995 RequireJS + Google Material Charts

### PR DESCRIPTION
**Pull request by GordonSmith**
Hack to work around google webfont issue:  https://github.com/typekit/webfontloader/issues/278

Fixes GH-995

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@dtsnell4 Please Review

http://rawgit.com/GordonSmith/Visualization/GH-995/demos/dermatology.html?src/google/Bar.material

**Comment by GordonSmith** [comment]
FYI - This is "broken" in IE, but due to a different issue:  https://github.com/google/google-visualization-issues/issues/2039

**Comment by GordonSmith** [comment]
Further:  These material charts are still really buggy...

**Comment by dtsnell4** [comment]
That's pretty clever and it seems to be working fine...  but if its hacky and buggy, do we really want to include it in the library at this point?

**Comment by GordonSmith** [comment]
Dunno - we might want a different grouping for the material charts anyway (rather than replacing the existing ones) - but it might just be there Bar chart is poor and things like the Gantt chart might be ok?

**Comment by mlzummo** [comment]
looks good to me

**Pull request merged**
