### PR TITLE
GH-1267 FILTER_BY_LABEL_DB_FIX

### PR DESCRIPTION
**Pull request by mlzummo**
Fixes the function from returning undefined (returns empty object instead)

Fixes GH-1267

Signed-off-by: Mathew Zummo <mzummo@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
I think I would prefer it to return null rather than undefined or an empty object so that the caller knows that nothing was found.

**Comment by mlzummo** [comment]
@GordonSmith so we want to keep the commserror we get then?

**Comment by GordonSmith** [comment]
Well that error probably means something?

**Comment by mlzummo** [comment]
well the error i think occurs cause the idx its looking for isnt loaded until click ... its looking for {}.idx where {} is the object its suppose to return ... i just return an object instead of undefined and then the just the idx will be undefined which is ok in this case

**Comment by GordonSmith** [comment]
The API for any field access is "get field by ..." where "..." could be "index" or "label" (or other options in the future).

If the field does not exist it *should* return null and not an empty object.

If this is causing an issue in other places, then the other places need to either be 100% sure that a field does exist or to test for its existence.

**Pull request closed without merging**
