### PR TITLE
GH-816 Allow properties to be functions

### PR DESCRIPTION
**Pull request by GordonSmith**
var myShape = new Shape()
  .colorFill(function() { return "red";})}
;

Fixes GH-695

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage Please Review - I refactored how the themes were working (I think I also fixed an issue with them:  Open Shap Widget, change theme, switch to Surface Widget, select default theme - would not reset),

**Comment by jbrundage** [comment]
Very good, the *origDefaultValue* implementation makes more sense than *trueDefaultValue*

I like the capability of "functions" as param values... how will this work with serialization? it wont attempt to turn the function into a string, will it?

**Comment by mlzummo** [comment]
looks good, looks like functions will be serialized as all props are "casted" into functions with d3.functor?

**Comment by jbrundage** [comment]
I'm assuming Persist will grab the *value* of a param to be serialized (the returned value from the function).

**Comment by drealeed** [comment]
Gordon, will this be used to support databomb aggregations, by defining functions in the ddl to perform sum, avg, max, etc?

**Comment by GordonSmith** [comment]
@drea nope - I was planning on using it for the axis text formatting (but turns out I had that issue solved already).
@jbrundage The value is what is serialized (and thus deserialized - which would replace the inline function with a value) - maybe the functor support is only for non published properties.
Hmmm I need to think about this a little bit more.

**Comment by GordonSmith** [comment]
Closing in favor of https://github.com/hpcc-systems/Visualization/pull/845 (which only has the theme fixes)

**Pull request closed without merging**
