### PR TITLE
GH-680 Fixes test-no-amd.html

### PR DESCRIPTION
**Pull request by mlzummo**
@GordonSmith Please Review

Fixes scatter and slider non-amd build issues

Signed-off-by: Mathew Zummo <mzummo@gmail.com>

### CODE REVIEW

**Comment by mlzummo** [comment]
requires: WORDCLOUD_BOWER #681 (not yet added) to fix word cloud issue

**Comment by mlzummo** [comment]
@GordonSmith should i change everything back to .min.js too, just noticed that

**Comment by mlzummo** [comment]
changed via GH editor, will rollup tomorrow.

**Comment by GordonSmith** [comment]
Looks good can you roll up to a single commit?

**Comment by mlzummo** [comment]
@GordonSmith ... ready for pull

**Pull request merged**
