### PR TITLE
GH-705 Fix table pagination

### PR DESCRIPTION
**Pull request by mlzummo**
@GordonSmith @buunguyen Please Review

Fix table pagination
Fixes GH-705

Signed-off-by: Mathew Zummo <mzummo@gmail.com>

### CODE REVIEW

**Comment by mlzummo** [comment]
I only have the option of rebasing against 1.4.4 now .... how should i do the rebase here to get this fix retroactive

**Comment by GordonSmith** [comment]
Rebase onto 1.4.4 and issue the PR onto candidate-1.4.4

**Comment by mlzummo** [comment]
closing and reissuing against 1.4.4

**Comment by buunguyen** [comment]
@mizummo is this merged in 1.4.4 yet?

**Pull request closed without merging**
