### PR TITLE
Add C3_Gauge.

### PR DESCRIPTION
**Pull request by GordonSmith**
Added 1DChart interface.

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo Please Review

**Comment by mlzummo** [comment]
besides .click() looks good.

**Comment by mlzummo** [comment]
this update breaks c3 bar chart

**Comment by mlzummo** [comment]
column still works ... bar and column should be merged into one anyways

**Comment by mlzummo** [comment]
looks good

**Comment by GordonSmith** [comment]
Rolled-up commits

**Pull request merged**
