### PR TITLE
Amcharts t2

### PR DESCRIPTION
**Pull request by mlzummo**
@GordonSmith @drealeed 

Please Review/Comment ... i don't think i did a proper rebase and it looks like a few charts arent loading in derm. will fix tomorrow ... please take a look in the meantime.

### CODE REVIEW

**Comment by mlzummo** [comment]
http://rawgit.com/mlzummo/Visualization/AMCHARTS-T2/demos/dermatology.html?src/other/Table

**Comment by mlzummo** [comment]
reminder: gordon can you show me where i went wrong with my rebase, i tried a shortcut from what i normally do and it messed it up had this happen before

**Comment by GordonSmith** [comment]
Dunno about your rebase, but I just did a rebase of you branch on upstream/master and "skipped" the Cached Request Issue as its already in updtream.  You can see/get my rebased branch here:  https://github.com/hpcc-systems/Visualization/pull/293

**Comment by GordonSmith** [comment]
@mlzummo Important:  Your missing the licence file and reading same you will need written permission to redistribute the sources.

**Pull request closed without merging**
