### PR TITLE
GH-1923 Add "vertical" align property for tables

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes GH-1923

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@senthilkumarperiasamy @jbrundage @jchambers-ln Please Review

**Comment by senthilkumarperiasamy** [comment]
@GordonSmith How can I test this change. I don't see vertical align property in table properties.

**Comment by GordonSmith** [comment]
@senthilkumarperiasamy http://rawgit.com/GordonSmith/Visualization/GH-1923/demos/dermatology.html?src/other/Table.widget&itemsPerPage=40&verticalAlign=top&minWidgetWidth=200&minWidgetHeight=200 (it needs to be set prior to the initial render)

**Comment by jbrundage** [comment]
Looks good to me

**Pull request merged**
