### PR TITLE
Adds Playground

### PR DESCRIPTION
**Pull request by mlzummo**
Signed-off-by: Mathew Zummo <mzummo@gmail.com>

### CODE REVIEW

**Comment by mlzummo** [comment]
to test locally:
1) git checkout PLAYGROUND
2) cd demos/ && bower install
3) npm install -g http-server
4) cd .. 
5) http-server ./
6) browse to http://localhost:8080/demos/playground.html

**Comment by GordonSmith** [comment]
Is there a rawgit for it?

**Comment by mlzummo** [comment]
yes @ this branch (added bower_components back in): http://rawgit.com/mlzummo/Visualization/PLAYGROUND_RGBC/demos/playground.html

**Comment by GordonSmith** [comment]
Can you move this to a subfolder in apps

**Comment by GordonSmith** [comment]
@mlzummo You don't have to keep closing and opening new PRs because your making changes.

**Pull request closed without merging**
