### PR TITLE
GH-829 Amcharts Axis Tick Formatting

### PR DESCRIPTION
**Pull request by mlzummo**
@GordonSmith @dtsnell4 @jbrundage @dineshshetye 

Please Review

Adds Y-Axis tick formatting to Amcharts

Fixes GH-829

Signed-off-by: Mathew Zummo <mzummo@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
We need to ensure that https://github.com/hpcc-systems/Visualization/pull/832 and this work the same way as far as is possible.

**Comment by mlzummo** [comment]
@GordonSmith I am using  d3.format(context.yAxisTickFormat())(d); which is how the HPCC charts do it

**Comment by mlzummo** [comment]
http://rawgit.com/mlzummo/Visualization/GH-829_AMCHART_AXIS_TICK_FORMATTING/demos/dermatology.html

**Comment by jbrundage** [comment]
I visited this page:
https://rawgit.com/mlzummo/Visualization/GH-829_AMCHART_AXIS_TICK_FORMATTING/demos/dermatology.html?src/amchart/Bar

I opened the console and executed this:
currWidget.data([["asdf",1234567890,1123456789]]).render()

The Y-Axis labels display **1.11G** to **1.25G**, by default I would expect it to be formatted to **1.11B** (for billion)

**Comment by GordonSmith** [comment]
@mlzummo If you look at the link I posted you will see it is different to what you would have looked at originally
@jbrundage Matt is defaulting to "s" which is "SI-Prefix" as per  https://github.com/mbostock/d3/wiki/Formatting

**Comment by mlzummo** [comment]
add optional flag and implement

**Comment by jbrundage** [comment]
I see, it just seems odd to use "mega" and "giga" rather than "million" and "billion"

**Comment by mlzummo** [comment]
@GordonSmith does d3 format support the not SI (US system) ?

**Comment by GordonSmith** [comment]
@jbrundage @mlzummo I would consider Million and Billion to be financial terms rather than specifiers of 10^n  You can however do things like "$.02f".

**Comment by mlzummo** [comment]
closing in favor of https://github.com/hpcc-systems/Visualization/pull/852

**Pull request closed without merging**
