### PR TITLE
Table Widget Fixed First Column

### PR DESCRIPTION
**Pull request by dtsnell4**
Added fixedColumns as publish parameter so user can choose either fixed first column, fixed header, or both.

Signed-off-by: Dan Snell <Dan.Snell@lexisnexis.com>

### CODE REVIEW

**Comment by dtsnell4** [comment]
@GordonSmith I rebased 1.6.0 on my branch, combine the commits, but there are still 10 commits showing

**Comment by GordonSmith** [comment]
@dtsnell4 When you rebased you needed to "skip" all the other commits (multi select and pick skip).

**Comment by dtsnell4** [comment]
How do I do that?  I've never heard of it...

**Comment by dtsnell4** [comment]
Sorry, what program are you referring to?

**Comment by GordonSmith** [comment]
Tortoise GIT is probably easiest:
image

**Comment by dtsnell4** [comment]
@GordonSmith fixed

**Comment by GordonSmith** [comment]
Which branch is this for?

**Comment by dtsnell4** [comment]
CLosing in favor of #803

**Pull request closed without merging**
