### PR TITLE
GH-1399 C3_PIE_FIX

### PR DESCRIPTION
**Pull request by mlzummo**
Removes data from C3 correctly while keeping selections
Fixes GH-1399

Signed-off-by: Mathew Zummo <mzummo@gmail.com>

### CODE REVIEW

**Comment by mlzummo** [comment]
@GordonSmith @jbrundage Please Review

**Comment by mlzummo** [comment]
closing in favor of https://github.com/hpcc-systems/Visualization/pull/1417

**Comment by mlzummo** [comment]
fixes dash c3 selection issue when reloading data into a pie

**Comment by GordonSmith** [comment]
@mlzummo Can you provide a link to an example of the issue (here or in the issue report).

**Comment by mlzummo** [comment]
@jbrundage can u link to the dashboard where this issue is/was present

**Comment by mlzummo** [comment]
https://securedev02.accurint.com/zummma01/dash1/avp/page/welcome

dash link can be generated here
https://securedev02.accurint.com/brundajx/scripts/dash/linkgen/index.php

if you click "dashboards"-> usage outcome and cick all the bars and then was switching bars with selections and all i was rendering blank slices and other issues. (the tes ti have right now up there also has the legends on the bottom" having them on th eleft cause the pie chart to render incorrectly out of the size of the div ... wasnt able to track that butmoving legend to bottom fixed that

**Comment by mlzummo** [comment]
the legend bottom fix is not in the PR (needs to done through DDL/Serialization"

**Comment by GordonSmith** [comment]
@mlzummo This "fix" will probably break all the c3 charts (if a chart is loaded with new data rows, the old ones won't be removed).

**Comment by GordonSmith** [comment]
```
c3Chart
.data([["Geog", 20]])
.render();
some time later
c3Chart
.data([["Geog2", 20]])
.render();
```

**Comment by GordonSmith** [comment]
Clsoing in favor of:  https://github.com/hpcc-systems/Visualization/pull/1441

**Pull request closed without merging**
