### PR TITLE
fix: Add deselection to ReactGantt

### LINKED ISSUE #3735: Timeline widgets need the option to unselect a selected range

### PR DESCRIPTION
**Pull request by jbrundage**
Fixes #3735

Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

## Checklist:
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit message includes a "fixes" reference if appropriate.
  - [x] The commit is signed.
- [x] The change has been fully tested:
  - [x] I have viewed all related gallery items
  - [ ] I have viewed all related dermatology items
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised new issues to address them separately

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage - Does this deselect on:
* Whitespace click (looks like yes?)
* Ctrl+click on previously selected item (maybe?)

**Comment by jbrundage** [comment]
It uses the same click selection behavior as MiniGantt. Clicking a selected item deselects it. (not on whitespace, and ctrl is ignored).

I'll look into adding the whitespace deselect, but should "Ctrl" need to be pressed while clicking to deselect?

**Comment by jbrundage** [comment]
@GordonSmith amended to include the two features you mentioned

**Comment by GordonSmith** [comment]
Good point - I was really shooting for the same behaviour...

**Comment by jbrundage** [comment]
@GordonSmith I've amended this PR to have the best of both worlds:
Clicking whitespace clears the selection (not a feature in MiniGantt)
Clicking a selected item deselects it (same as MiniGantt)

**Review by GordonSmith — APPROVED** [review]

**Pull request merged**
