### PR TITLE
GH-582 Table columns render in wrong sequence

### PR DESCRIPTION
**Pull request by GordonSmith**
Adding/removing or editing the columns will cause them to lose their correct order.

Fixes GH-582

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@buunguyen Please revie:  http://rawgit.com/GordonSmith/Visualization/GH-582/demos/dermatology.html?src/other/Table
(You can turn columns on and then edit it).

**Comment by buunguyen** [comment]
LGTM.

@dunguyen-kms this should fix the problem you're having.

**Comment by mlzummo** [comment]
im curious as to "why" this fixes the issue?

**Comment by buunguyen** [comment]
My review is probably lame (I'm not familiar with d3). Just run a [quick test](http://jsfiddle.net/y17p8dbn/), it appears that this fix, while solving the reordering, has an issue: existing data won't get replaced (i.e. I expect to see 0, 1, 3 in my test but it still shows 0, 1, 2). Hope @GordonSmith can shed some light.

**Comment by mlzummo** [comment]
that sounds above right, i recall it specially being changed to what it is now becuase of that

**Comment by GordonSmith** [comment]
@buunguyen Your quickTest is not using the "3 stages" of the d3 selectAll.data pattern.  See https://jsfiddle.net/y17p8dbn/1/ for the working version.

**Comment by GordonSmith** [comment]
@mlzummo Can you re-issue that missing ";" fix against candidate-1.4.4?

**Comment by buunguyen** [comment]
@GordonSmith your example shows 0, 1, 2 instead of 0, 1, 5, 6. Is it the expected behavior?

**Comment by GordonSmith** [comment]
remove the "s" from the http and try again<g>.

**Comment by GordonSmith** [comment]
Final review still needed....

**Comment by buunguyen** [comment]
To be honest, I'm not clear why it works the way it does. I remove the `exit()` from your example (i.e. break the 3 stage pattern) and it appears to still work http://jsfiddle.net/u9m0fsrn/. That said, this fix seems to achieve the effect and that's probably good enough.

Guess I should pick up some more d3 knowledge :).

**Comment by GordonSmith** [comment]
In that example exit is never called beause the number of "p" elements only got longer.
This example would have an exit:  http://jsfiddle.net/u9m0fsrn/1/

**Pull request merged**
