### PR TITLE
GH-1655 Add runtime "set" support

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes GH-1655

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage Please Review

**Comment by jbrundage** [comment]
Looks good, but the contents of PropertyExt.js could be made to be more readable.

**Comment by GordonSmith** [comment]
@jbrundage What do you mean?

**Comment by jbrundage** [comment]
@GordonSmith I just meant the code in some of the core js files are written in such a way that it's difficult to follow the logic flow.

**Pull request merged**
