### PR TITLE
Adds new rendercallback feature

### PR DESCRIPTION
**Pull request by mlzummo**
@GordonSmith @jbrundage @drealeed @dtsnell4 @dineshshetye 

Please Review

Signed-off-by: Mathew Zummo <mzummo@gmail.com>

### CODE REVIEW

**Comment by mlzummo** [comment]
this will be redone by @GordonSmith with new event method as well (slated for 2.0)

**Comment by GordonSmith** [comment]
FYI - I have the new event mechanism in place now and am testing, we will need to discuss a release schedule for it as 99% of the breaking changes are internal.

**Comment by GordonSmith** [comment]
@mlzummo Rebase is still needed and I will pull.

**Comment by mlzummo** [comment]
closing waiting for gordon impl.

**Pull request closed without merging**
