### PR TITLE
GH-1388 Prevent duplicate PP serialization

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes GH-1388

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo @jbrundage Please Review

**Comment by jbrundage** [comment]
@GordonSmith Great, looks good

**Comment by mlzummo** [comment]
@GordonSmith looks good... but i have a few things im doing right now... what cuased us to have to do this?

**Comment by mlzummo** [comment]
in ext we could set it so we could override props or does this compeltely delete all props?

**Comment by GordonSmith** [comment]
In this case the same widget was being "published" by more than one PP.

**Pull request merged**
