### PR TITLE
GH-211 Use visualization title if it exists

### LINKED ISSUE #211: If a chart has a "title" attribute, that should be used in the header bar rather than dashboard name
Charts frequently have titles specified; if a title exists for a chart, it should show up in the header bar rather than the chart name.

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes #211

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@drealeed Please Review

**Comment by drealeed** [comment]
if there's no title given, does it default to id?

**Comment by GordonSmith** [comment]
Yes.

**Comment by drealeed** [comment]
reviewed & signed off

**Pull request merged**
