### PR TITLE
Add encoding to URL params.

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage @mlzummo Please Review (Fixes the dermatology url sync issue).

**Comment by jbrundage** [comment]
@GordonSmith this didn't fix the issue

**Comment by mlzummo** [comment]
the URL is going to be way to large too ... better to skip that one publish param

**Comment by GordonSmith** [comment]
This fix includes max URI test as well now.

**Comment by mlzummo** [comment]
@GordonSmith can you pull this now, not having this fix is driving me nutz

**Comment by GordonSmith** [comment]
Sure - it was just waiting on a review.

**Pull request merged**
