### PR TITLE
Upgrade to latest version of d3-cloud

### PR DESCRIPTION
**Pull request by GordonSmith**
d3-cloud now supports AMD loading, so removing special handling.

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo please review

**Comment by mlzummo** [comment]
looks good

**Comment by mlzummo** [comment]
needs to be added to dermatology so we can test it

**Comment by GordonSmith** [comment]
http://rawgit.com/GordonSmith/Visualization/WORDCLOUD_BOWER/demos/dermatology.html?src/other/WordCloud

**Comment by mlzummo** [comment]
looks good ... can we pull that now?

**Pull request merged**
