### PR TITLE
GH-1322 Remove UT console messages

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
not 100% there yet, but this + https://github.com/hpcc-systems/Visualization/pull/1421 makes a big improvement.

**Comment by GordonSmith** [comment]
The travis failure is fixed by the MegaChart resize PR - the combined PRs look like this:
https://travis-ci.org/GordonSmith/Visualization/builds/106147893

**Comment by mlzummo** [comment]
@GordonSmith i got this same travis error earlier you need to rebase on 1.10

**Comment by GordonSmith** [comment]
Rebased

**Comment by mlzummo** [comment]
@GordonSmith lets pull it

**Pull request merged**
