### PR TITLE
GH-986 Travis Build Error

### PR DESCRIPTION
**Pull request by GordonSmith**
Package versions should be locked down to point releases.
In this case the d3-cloud went from 1.1.2 to 1.2.0

Fixes GH-986

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo @jbrundage Please Review

**Comment by mlzummo** [comment]
while i agree that we need to do this i think not bumping the d3 cloud version and fixing the issues that it brings is just delaying the inevitable

**Comment by GordonSmith** [comment]
We will bump the cloud version at some point (like we do when we bump am charts) - but not in the 1.6.x branch.

IOW Open an issue "Update d3-cloud to latest version."

**Comment by GordonSmith** [comment]
@mlzummo @jbrundage Please Review (bump)

**Comment by jbrundage** [comment]
Looks good to me. I'm excited to put these Travis issues in the past.

**Pull request merged**
