### PR TITLE
GH-1264 Hides widgets while Grid in designMode

### PR DESCRIPTION
**Pull request by jbrundage**
Fixes GH-1264

@mlzummo please review

http://rawgit.com/jbrundage/Visualization/GH-1264/demos/dermatology.html?src/layout/Grid&designMode=true

Signed-off-by: jay <jbrundage372@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
Does this change the performance at all?  As a quick fix, I was thinking of adding a long debounce to the resize method of the inner widgets, which would effectively prevent them from being redrawn until an idle moment.

**Comment by jbrundage** [comment]
@GordonSmith I like the idea of resizing-on-idle

**Comment by jbrundage** [comment]
@GordonSmith Using the marshaller/HTML.databomb as a test case... this PR enters/exits designMode 15% faster

**Comment by jbrundage** [comment]
@GordonSmith Grid Cell dragHandles are now appropriately styled on **enter**, allowing designMode to load much faster.

**Comment by mlzummo** [comment]
looks good needs rebase

**Comment by GordonSmith** [comment]
@jbrundage @mlzummo @dtsnell4 - This code is probably ok to pull now - but is it still needed with the overall improvements in the PE speed?  Alternatively we could make this a soft option by adding PP "hide contents while designing"?

**Comment by GordonSmith** [comment]
@jbrundage Needs rebase and if you can make this optional with a PP I will pull.

**Pull request merged**
