### PR TITLE
GH-1760 IndicateTheseIds catches all mouse events

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes GH-1760

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage @jchambers-ln Please Review

**Comment by mlzummo** [comment]
@GordonSmith could you explain this code a bit ... thought this to not catch all mouse events but i dont follow the changes

**Comment by GordonSmith** [comment]
@mlzummo - The actual fix was to add ```pointer-events: none``` to the style sheets.  But I also refactored the styles from being specific to each DOM element, into its own style sheet (and tweaked the look at the same time)..

**Comment by jbrundage** [comment]
Looks good to me

**Pull request merged**
