### PR TITLE
Euro OSS Choropleth

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo @jbrundage Please Review

**Comment by mlzummo** [comment]
text.js:307 GET http://rawgit.com/GordonSmith/Visualization/MAP_GBR/src/map/TopoJSON/FR_idx.json 404 (Not Found)

(also no click support?)

**Comment by mlzummo** [comment]
dtagging causes these: errors: GET http://rawgit.com/GordonSmith/Visualization/MAP_GBR/demos/dermatology.html?…Lat=44.81102011086648&centerLong=5.352572667798384&zoom=15.999407472091477 503 (Service Temporarily Unavailable)

**Comment by mlzummo** [comment]
@GordonSmith @jbrundage 

this is going to require a phone meeting to discuss

**Comment by GordonSmith** [comment]
1.  The 404s are expected - the Index files are optional (and we will add more over time).
2.  The 503 is a GitHub services issue?
3.  I will rebase to fix the travis.

**Comment by GordonSmith** [comment]
Please re-submit PR for 1.14.0

**Comment by GordonSmith** [comment]
Closing in favor of:  https://github.com/hpcc-systems/Visualization/pull/1528

**Pull request closed without merging**
