### PR TITLE
feat(readme): Add README.md and samples for other

### PR DESCRIPTION
**Pull request by jbrundage**
Resolved d3-ease issue with common/src/Transition.ts (for MorphText)

Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

## Checklist:
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit message includes a "fixes" reference if appropriate.
  - [x] The commit is signed.
- [x] The change has been fully tested:
  - [x] I have viewed all related gallery items
  - [x] I have viewed all related dermatology items
- [x] There are no similar instances of the same problem that should be addressed
  - [x] I have addressed them here
  - [x] I have raised new issues to address them separately

## Testing:
I've tested the README.md stand-alone HTML in codepen and opened an issue related to one of the samples that the README.md file links to.

### CODE REVIEW

**Comment by GordonSmith** [comment]
What new issues were raised?

**Comment by jbrundage** [comment]
#3066

**Comment by GordonSmith** [comment]
@jbrundage failing tests

**Comment by jbrundage** [comment]
It looks like `simpleheat` isn't available for some reason? https://travis-ci.org/hpcc-systems/Visualization/builds/475399834#L2308

...but it loads just fine when viewing it in the gallery.

**Comment by GordonSmith** [comment]
Closing in favor of:  https://github.com/hpcc-systems/Visualization/pull/3092

**Pull request closed without merging**
