### PR TITLE
GH-1848 Refactor request calculation

### PR DESCRIPTION
**Pull request by GordonSmith**
Add support for HIPIE mappings in events.

Fixes GH-1848

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jchambers-ln, @jbrundage, @mlzummo Please review

**Comment by jchambers-ln** [comment]
From a code point of view it looks good, I don't know the work flow in your code base here well enough to know if it solves the issue.

If I checkout GordonSmith:GH1848-v1.10.10 and deploy it in DSP will that contain everything that would be rc3?

**Comment by GordonSmith** [comment]
Yes

**Comment by jchambers-ln** [comment]
ok making a build now with the fix in it

**Comment by jchambers-ln** [comment]
I checked out your branch and ran
npm install && npm update && bower install && bower update

but I don't see the dist-amd folder after building...

**Comment by jchambers-ln** [comment]
nm ran gulp build-all and now it is there

**Comment by GordonSmith** [comment]
You beat me to it - there are some instructions here:  https://github.com/hpcc-systems/Visualization/wiki/Building-a-Release

**Comment by jchambers-ln** [comment]
I was looking at that as I don't do it often enough to remember the commands -- the gulp build-all is under the AM lic version may want to edit that to clarify

**Comment by jchambers-ln** [comment]
With this build widgets with a form filter do not load their default filter on page load.

**Comment by jchambers-ln** [comment]
In firebug using the minifed you get
TypeError: this._ddlDashboards[a].visualizations is undefined
...;for(var a in this._ddlDashboards){var s=Math.floor(Math.sqrt(this._ddlDashboard...
hpcc-vi...ller.j

**Comment by jchambers-ln** [comment]
chrome you get
hpcc-viz-marshaller.js:2 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined(…)

**Comment by jchambers-ln** [comment]
using sources
Chrome:
HTML.js:25 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined(…)

Firefox:

"NetworkError: 404 Not Found - http://localhost:8080/DSP/js/Visualization/src/d3-tip.js"
d3-tip.js
Error: Script error for "d3-tip", needed by: src/api/ITooltip
http://requirejs.org/docs/errors.html#scripterror
	

var e = new Error(msg + '\nhttp://requirejs.org/docs/errors.html#' + id);

**Comment by jchambers-ln** [comment]
Sent you an email to a build of that dashboard with public data

**Comment by jchambers-ln** [comment]
After rebuilding off GH1848-v1.10.10 it is stable and the issue is resolved -- I tested other items and it seems solid

**Pull request merged**
