### PR TITLE
Support Databomb Format II

### LINKED ISSUE #328: Table only shows two rows.
I think we should default the table pagination by default (or at least resize the number of rows to fit the available space).

### LINKED ISSUE #337: Databomb II
Support latest databomb DDL format.

### PR DESCRIPTION
**Pull request by GordonSmith**
Add support for databomb named outputs.
Default table pagination to off.

Fixes #337
Fixes #328

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@drealeed Please Review
Test Page:  http://rawgit.com/GordonSmith/Visualization/GH-337_DatabombII/demos/dermatology.html?src/marshaller/Graph

**Comment by GordonSmith** [comment]
@mlzummo Please Review the "Table" fixes.

**Comment by mlzummo** [comment]
Looks good

**Comment by drealeed** [comment]
Excellent!! Looks lovely! Looking forward to using it.

**Pull request merged**
