### PR TITLE
Adds support for SVGWidget draw start pos to be modified

### PR DESCRIPTION
**Pull request by mlzummo**
Signed-off-by: Mathew Zummo <mzummo@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
What about HTML Widgets?

**Comment by mlzummo** [comment]
HTML Widgets don't seem to be be effected by this, and no where in the code for HTMLWidget do I see anything that would hint that it draws from the center out.

**Comment by mlzummo** [comment]
Or would you like me to add center capability to HTMLWidget... HTML doesn't behave like SVG does in regards to this

**Comment by GordonSmith** [comment]
Was wondering if you had thought about it...  I suspect they should both work the same.  This change may simplify several of the widgets (which go out of their way to offset by width / 2 and height /2

**Comment by mlzummo** [comment]
can you link/show me to the widget(s) that go out of there way to offset their width, so I can take a look at the code around that?

**Comment by GordonSmith** [comment]
Dendrogram.js

**Comment by mlzummo** [comment]
i never did understand that with the dendrogram, the SVGwidget itself is already set to draw from center by default and the dendrogram goes and does it yet again, (I am actually running a modified version of the dendrogram right now due to alignment and fitting issues) ... are there any HTMLWidgets that are set to draw from the center?

**Pull request closed without merging**
