### PR TITLE
Sunburst not resizing.

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo, @jbrundage  Please Review

**Comment by mlzummo** [comment]
renders as a circle - 
image

**Comment by GordonSmith** [comment]
Fixed issues with dermatology, thx - please re-review

**Comment by mlzummo** [comment]
works, however the SVG container does not resize, the widget itself is zoomed in on, is that what your shooting for?
code used:
widget.size({width:500,height:500}).render();

**Comment by GordonSmith** [comment]
No - when the outer container is resized the inner viz didn't...

**Pull request merged**
