### PR TITLE
GH-1328 ZN_Graph table corruption

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes GH-1328

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo Please Review

**Comment by mlzummo** [comment]
i need to test this with the DSP team.

**Comment by mlzummo** [comment]
@GordonSmith this does not seem to be fixing the ZN_Graph (relevent dash console log errors)

**Comment by GordonSmith** [comment]
This doesn't fix any console errors - it fixes the table not rendering correctly issue, see:  https://github.com/hpcc-systems/Visualization/issues/1328

**Comment by mlzummo** [comment]
looks good then

**Pull request merged**
