### PR TITLE
GH-1342 Improve HIPIE mapping console errors

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes GH-1342

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo @jbrundage Please Review

**Comment by mlzummo** [comment]
looks good but @jbrundage can you test this against the code you were having issues with

**Comment by jbrundage** [comment]
Sure, one moment

**Comment by jbrundage** [comment]
@GordonSmith This code change looks good

@mlzummo Unfortunately it didn't resolve the DASH issue

**Pull request merged**
