### PR TITLE
fix(XYAxis): Range selection issues

### PR DESCRIPTION
**Pull request by GordonSmith**
* When yAxis is hidden the LHS handle fails to display.
* Resizing can leave the blue selection rectangle at the wrong size.

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

## Checklist:
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit message includes a "fixes" reference if appropriate.
  - [x] The commit is signed.
- [x] The change has been fully tested:
  - [ ] I have viewed all related gallery items
  - [ ] I have viewed all related dermatology items
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised new issues to address them separately

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage Will this break the 2D selection mode?

**Comment by GordonSmith** [comment]
@jbrundage bump

**Comment by jbrundage** [comment]
Actually it does seem to cause problems with 2d selection. I'll investigate.

**Comment by GordonSmith** [comment]
@jbrundage any updates?

**Comment by GordonSmith** [comment]
@jbrundage did your investigation conclude anything?

**Pull request closed without merging**
