### PR TITLE
GH-646 Layered Layout

### PR DESCRIPTION
**Pull request by GordonSmith**
Added AbsoluteSurface

Fixes GH-646

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage @mlzummo @dtsnell4 Please Review
http://rawgit.com/GordonSmith/Visualization/LAYOUT_LAYERS/demos/dermatology.html?src/layout/Layered
http://rawgit.com/GordonSmith/Visualization/LAYOUT_LAYERS/demos/dermatology.html?src/layout/AbsoluteSurface

Note:  It does have a dependency on https://github.com/hpcc-systems/Visualization/pull/631

**Comment by dtsnell4** [comment]
Looks fine to me

**Comment by jbrundage** [comment]
Neat, it looks good to me, but how do you control the z-index of the widgets?

**Comment by GordonSmith** [comment]
Yea could do with a move up/back/top/bottom.

**Comment by GordonSmith** [comment]
Rebased and ensured that the z-order matches the widgets order (the user can simply sort as they see fit as per testData...

**Pull request merged**
