### PR TITLE
Simple Leak Checking.

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage Please Review

http://rawgit.com/GordonSmith/Visualization/LEAK_CHECKING/demos/dermatology.html?hpcc_debug=1

**Comment by mlzummo** [comment]
@GordonSmith where will this be used?

**Comment by GordonSmith** [comment]
Buy developers who want to check that every widget that was assigned to a target was also cleaned up correctly (it only works when hpcc_debug === true).

**Comment by mlzummo** [comment]
looks good

**Pull request merged**
