### PR TITLE
feat(column): Add option to show percent values

### LINKED ISSUE #2969: Show percentages in bar chart
Would it be possible to show % values in the bar charts similarly to how we can currently 'showValue'?

Something along the lines of this:

image

### PR DESCRIPTION
**Pull request by jbrundage**
Fixes #2969

Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

### CODE REVIEW

**Comment by jbrundage** [comment]
image
This makes sense for single series data with no negative values.

**Comment by jbrundage** [comment]
@GordonSmith added a sample. It does make sense in some cases to use `showValueType("domain")`.

image

**Comment by jbrundage** [comment]
@GordonSmith can we pull this? This solves the Cop Logic request and the `showValueType("domain")` likely won't be used most of the time but it's a convenience feature that could possibly be just what someone is looking for.

**Comment by GordonSmith** [comment]
Closing in favor of:  https://github.com/hpcc-systems/Visualization/pull/2992

**Pull request closed without merging**
