### PR TITLE
GH-508  XAxis Scales

### PR DESCRIPTION
**Pull request by GordonSmith**
Add support for linear scale.
Add support for time scale.
Publish "sample" data property.

Fixes GH-508

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo @anmoljagetia Please Review

**Comment by mlzummo** [comment]
looks good, however with the separation of testData from the widgets comming, are you sure you want to start the trend of having a new sample data publish param now, doesn't seem appropriate? (though it does make it easy for testing/demoing)

**Comment by mlzummo** [comment]
... unless this is going to tie into the new testData format later on down the road?

**Comment by anmoljagetia** [comment]
Looks good. The sampleData has a blank category before the three options, should we keep that ?

**Comment by GordonSmith** [comment]
@mlzummo I had the same thought - but since it will get replaced by something new, its a step in the right direction?

**Comment by GordonSmith** [comment]
@anmoljagetia - Yes as the default should be no sample data.

**Pull request merged**
