### PR TITLE
Sunburst Double Click Issues

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo, @jbrundage Please Review

**Comment by mlzummo** [comment]
There are errors on dblclick and on widget first load in arcTweenFunc ... this also prevents doubleclick event from working. 

Uncaught TypeError: undefined is not a functionSunburstPartition.js:113 SunburstPartition.arcTweenFuncSunburstPartition.js:26 SunburstPartition.rootSunburstPartition.js:107 dblclickd3.js:1120 (anonymous function)

**Comment by GordonSmith** [comment]
Thx - Can you try again:  http://rawgit.com/GordonSmith/Visualization/SUNBURST_DBLCLICK/demos/dermatology.html?src/tree/SunburstPartition

**Comment by mlzummo** [comment]
looks good, how does the double-click on that work i don't recognize whats it doing besides moving and changing colors

**Comment by GordonSmith** [comment]
On complex "trees" it allows you to zoom into the lower branches...

**Pull request merged**
