### PR TITLE
GH-847 Google map zoom to fit issue

### PR DESCRIPTION
**Pull request by GordonSmith**
Zoom to fit still expected old format.

Fixes GH-847

Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by mlzummo** [comment]
was the issue it was just not working because it was in gmapgraph? only diff i see is that we pass this.data() to zoomtofit now: https://github.com/GordonSmith/Visualization/blob/GH-847/src/map/GMap.js#L379

**Comment by GordonSmith** [comment]
The internal data shape changed from an array of json to a regular array

**Comment by GordonSmith** [comment]
@mlzumm Please Review

**Comment by mlzummo** [comment]
looks good

**Pull request merged**
