### PR TITLE
GH-835 Google Axis Ticks Formatting

### PR DESCRIPTION
**Pull request by dtsnell4**
Changes the publish param for axis formatting from "string" to "set".

Fixes GH-835

Signed-off-by: Dan Snell <Dan.Snell@lexisnexis.com>

### CODE REVIEW

**Comment by dtsnell4** [comment]
@GordonSmith @jbrundage @mlzummo Matt is correct, Google does not support d3.format, however it does have its own formatting options.  I noticed however the publish param was set to "string" instead of "set", so I fixed that.  Should it be a different issue?

**Comment by dtsnell4** [comment]
Although, we could make the publish param set the equivalent d3.format specifiers, and just translate them in the code to Google's format.  If the objective is to keep the interface pure d3 for the devs.

**Comment by mlzummo** [comment]
the problem with that is d3 supports alot more than what google offers in the formatting area prolly?

**Comment by jbrundage** [comment]
The publish parameters xAxisFormat and yAxisFormat should be xAxisTickFormat and yAxisTickFormat to match the other chart libraries

**Comment by dtsnell4** [comment]
@mlzummo I agree, which is why I suggested making it a set, so they only have the corresponding options.  Probably irrelevant, just throwing it out there.  @jbrundage I will change the names.

**Comment by jbrundage** [comment]
On second thought, since those two parameters are sets of predefined format types it may be a better idea to name them something along the lines of xAxisFormatType and yAxisFormatType.

**Comment by dtsnell4** [comment]
@jbrundage ok I'll wait...  @GordonSmith @mlzummo your thoughts?

**Comment by mlzummo** [comment]
don't name them the same as the rest of the charts becuase that will cause confusion when switching charts and them wondering why its not working ....

**Comment by GordonSmith** [comment]
@mlzummo @jbrundage Please re-review

**Comment by mlzummo** [comment]
looks good

**Pull request merged**
