### PR TITLE
GH-2030 Gridster Style Layout

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@jbrundage Please Review:  http://rawgit.com/GordonSmith/Visualization/GH-2030/demos/dermatology.html?src/layout/Grid.simple&designMode=false&surfaceBackgroundColor=white

**Comment by jbrundage** [comment]
Looks good to me!

**Comment by mlzummo** [comment]
looks good

**Comment by GordonSmith** [comment]
(rebased)

**Pull request merged**
