### PR TITLE
Test for valid class names

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordon.smith@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@mlzummo, @jbrundage, @dtsnell4, @buunguyen - Welcome to unit testing.

@anmoljagetia Has just added a base unit testing framework (mocha, chai, phantomjs) which "we" will be augmenting as time goes on.  This is my first test case and it caught 1 missing class name...

Please Review.

**Comment by buunguyen** [comment]
:+1: awesome work!

BTW, did you consider using [Karma](https://github.com/karma-runner/karma) as the test runner? Might not be important now, but if we need to run tests on other browsers (e.g. Chrome, IE), instead of only PhantomJS, it is simple to set up with Karma.

**Comment by GordonSmith** [comment]
Not yet as the main priority was to get it working with phantomJS on travis-ci.  Also inhouse our QA folks are using selenium I believe.

**Comment by mlzummo** [comment]
looks good

**Comment by GordonSmith** [comment]
Rebased

**Pull request merged**
